(() => {
  "use strict";
  const BUILD="14.4.4-rc4", COLLECTION="accesos";
  const states={NONE:"Sin credenciales",CREATED:"Credenciales creadas",INVITED:"Invitación enviada",ACTIVE:"Activo",SUSPENDED:"Suspendido",MAIL_PENDING:"Correo pendiente"};
  const activityByUid=new Map();
  const now=()=>new Date().toISOString(),clean=v=>String(v??"").trim(),normalized=v=>clean(v).toLowerCase();
  const html=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const formatDate=v=>v?new Date(v).toLocaleString("es-EC",{dateStyle:"medium",timeStyle:"short"}):"Sin registro";
  const close=dialog=>{if(dialog.open)dialog.close();dialog.remove()};
  const territoryFor=row=>(data.territorios||[]).find(x=>x.id===row?.territorioId)||(data.territorios||[]).find(x=>normalized(x.provincia)===normalized(row?.provincia)&&normalized(x.canton)===normalized(row?.canton));
  const activity=row=>row?.authUid?activityByUid.get(row.authUid):null;
  function lifecycle(row){if(!row?.authUid)return states.NONE;if(row.estadoAcceso===states.SUSPENDED||row.estadoPerfil==="Suspendido")return states.SUSPENDED;if(activity(row)?.primerAccesoEn)return states.ACTIVE;if(row.estadoAcceso===states.MAIL_PENDING)return states.MAIL_PENDING;if(row.invitacionEnviadaEn)return states.INVITED;return states.CREATED}
  function stateBadge(state){const style=state===states.ACTIVE?"success":state===states.SUSPENDED?"danger":[states.INVITED,states.MAIL_PENDING].includes(state)?"warn":"neutral";return `<span class="badge ${style}">${html(state)}</span>`}
  async function loadActivity(){activityByUid.clear();if(!isAdmin())return;try{const snap=await db.collection(COLLECTION).get();snap.forEach(doc=>activityByUid.set(doc.id,{uid:doc.id,...doc.data()}))}catch(error){console.warn("No fue posible consultar la actividad de acceso",error)}}
  async function recordCurrentAccess(){const user=auth.currentUser;if(!user)return;try{const state=window.SmartRiskScope?.getState?.()||{},profile=state.profile||currentProfile||{},ref=db.collection(COLLECTION).doc(user.uid),snap=await ref.get(),stamp=now(),payload={uid:user.uid,correo:normalized(user.email),nombre:profile.nombre||user.displayName||"",rol:profile.rol||state.role||"",scopeType:state.scopeType||"",version:BUILD,ultimoAccesoEn:stamp};if(!snap.exists)payload.primerAccesoEn=stamp;await ref.set(payload,{merge:true})}catch(error){console.warn("No fue posible registrar el acceso",error)}}
  function injectIdentity(){window.SMART_RISK_BUILD={version:BUILD,branch:"preview-rc14.4.4",module:"access-and-actions-r023"};const brand=document.querySelector(".brand span");if(brand)brand.textContent="CZ5 · Piloto controlado · RC14.4.4";const account=document.querySelector(".account-menu");if(account&&!document.querySelector(".build-chip")){const chip=document.createElement("span");chip.className="build-chip";chip.textContent="RC14.4.4 RC4";chip.title="Vista aislada con accesos personales y Acciones R02.3";account.prepend(chip)}if(document.querySelector("#smartrisk-access-styles"))return;const style=document.createElement("style");style.id="smartrisk-access-styles";style.textContent=`.build-chip{font-size:.72rem;font-weight:800;padding:.35rem .55rem;border:1px solid #c9d8e8;border-radius:999px;background:#f4f8fc;color:#29455f;white-space:nowrap}.access-summary{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:.75rem;margin:1rem 0}.access-summary button{display:flex;flex-direction:column;align-items:flex-start;gap:.2rem;padding:.9rem;border:1px solid #dce5ed;border-radius:14px;background:#fff;color:inherit;text-align:left}.access-summary button.active{outline:2px solid #315d7e;outline-offset:1px}.access-summary strong{font-size:1.45rem}.access-summary small{color:#637383}.access-toolbar{display:grid;grid-template-columns:1fr minmax(190px,auto) auto;gap:.65rem;align-items:center}.access-actions{display:flex;flex-wrap:wrap;gap:.4rem}.access-actions button{padding:.42rem .62rem;font-size:.78rem}.access-meta{display:block;color:#687887;font-size:.76rem;margin-top:.25rem}.access-warning{padding:.8rem 1rem;border-radius:12px;background:#fff7df;border:1px solid #ecd79a;margin:.75rem 0}.access-scope{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.access-scope .full{grid-column:1/-1}.access-security-note{padding:.8rem 1rem;background:#eef6f8;border-radius:12px;border:1px solid #c9e1e5;font-size:.88rem}.access-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem}.access-detail-grid article{padding:.85rem;border:1px solid #dce5ed;border-radius:12px;background:#fafcfd}.access-detail-grid small{display:block;color:#637383}.access-detail-grid b{display:block;margin-top:.2rem;word-break:break-word}@media(max-width:900px){.access-summary{grid-template-columns:1fr 1fr}.access-toolbar,.access-scope,.access-detail-grid{grid-template-columns:1fr}.access-scope .full{grid-column:auto}}`;document.head.appendChild(style)}
  async function updateProfile(row,extra={}){if(!row.authUid)return;const territory=territoryFor(row),profileState=row.estadoAcceso===states.SUSPENDED?"Suspendido":"Activo";await db.collection("perfiles").doc(row.authUid).set({correo:normalized(row.correo),nombre:clean(row.nombre),rol:row.rol,provincia:row.provincia,canton:row.canton,territorioIds:territory?.id?[territory.id]:[],estado:profileState,accesoEstado:row.estadoAcceso||states.CREATED,actualizadoEn:now(),actualizadoPor:session?.email||"",...extra},{merge:true})}
  async function provision(row){const app=firebase.initializeApp(firebaseConfig,`smartrisk-invite-${crypto.randomUUID()}`);let user=null;try{const credential=await app.auth().createUserWithEmailAndPassword(normalized(row.correo),`CZ5-${crypto.randomUUID()}!aA1`);user=credential.user;await user.updateProfile({displayName:clean(row.nombre)});row.authUid=user.uid;row.estadoAcceso=states.CREATED;row.credencialesCreadasEn=now();row.credencialesCreadasPor=session?.email||"";await updateProfile(row,{creadoEn:row.credencialesCreadasEn,creadoPor:row.credencialesCreadasPor});try{await auth.sendPasswordResetEmail(normalized(row.correo),{url:location.origin+location.pathname});row.estadoAcceso=states.INVITED;row.invitacionEnviadaEn=now();row.invitacionEnviadaPor=session?.email||"";await updateProfile(row,{accesoEstado:row.estadoAcceso,invitacionEnviadaEn:row.invitacionEnviadaEn});return{mailSent:true}}catch(mailError){row.estadoAcceso=states.MAIL_PENDING;await updateProfile(row,{accesoEstado:row.estadoAcceso});return{mailSent:false,mailError}}}catch(error){if(user)try{await user.delete()}catch{}row.authUid="";throw error}finally{try{await app.auth().signOut()}catch{}try{await app.delete()}catch{}}}
  async function resend(row){if(!row?.authUid)return;if(lifecycle(row)===states.SUSPENDED){alert("Reactiva el acceso antes de reenviar la invitación.");return}try{await auth.sendPasswordResetEmail(normalized(row.correo),{url:location.origin+location.pathname});row.estadoAcceso=states.INVITED;row.invitacionEnviadaEn=now();row.invitacionEnviadaPor=session?.email||"";await updateProfile(row,{accesoEstado:row.estadoAcceso,invitacionEnviadaEn:row.invitacionEnviadaEn});auditChange("REENVIAR_INVITACION","usuario",row.id,row.correo);save();alert("Se envió un nuevo enlace para definir la contraseña.");render()}catch(error){alert(firebaseMessage(error))}}
  async function toggle(row){if(!row?.authUid)return;const suspend=lifecycle(row)!==states.SUSPENDED,action=suspend?"suspender":"reactivar";if(!confirm(`¿Confirmas ${action} el acceso de ${row.nombre}?`))return;try{row.estadoAcceso=suspend?states.SUSPENDED:(activity(row)?.primerAccesoEn?states.ACTIVE:states.INVITED);row.estadoPerfil=suspend?"Suspendido":"Activo";row.accesoActualizadoEn=now();row.accesoActualizadoPor=session?.email||"";await updateProfile(row);auditChange(suspend?"SUSPENDER_ACCESO":"REACTIVAR_ACCESO","usuario",row.id,row.correo);save();render()}catch(error){alert(firebaseMessage(error))}}
  window.SmartRiskAccess={BUILD,COLLECTION,states,activityByUid,now,clean,normalized,html,formatDate,close,territoryFor,activity,lifecycle,stateBadge,loadActivity,recordCurrentAccess,updateProfile,provision,resend,toggle};
  injectIdentity();setTimeout(recordCurrentAccess,0);
})();