window.ENOS_IMPORT={id:"ENOS-2026-2027-PILOTO-01",label:"Paquete ENOS Zona 5 2026-2027",sites:[
["BF-01","La Pradera","San Jacinto de Buena Fe","La Pradera","Inundación / lluvias intensas","Medio","Alto",65,"viviendas, agua y energía",-0.922531,-79.500062],
["BF-02","Sector Rosa Amelia","San Jacinto de Buena Fe","Sector Rosa Amelia","Inundación / lluvias intensas","Alto","Alto",24,"población, vías y producción",-0.887386,-79.483324],
["BF-03","Santa Martha","11 de Octubre","Santa Martha","Inundación / lluvias intensas","Bajo","Bajo",123,"población y viviendas",-0.898069,-79.487444],
["BF-04","Sector 30 de Agosto","San Jacinto de Buena Fe","30 de Agosto","Inundación / lluvias intensas","Medio","Medio",6,"población, viviendas y agua",-0.8998,-79.484084],
["BF-05","Las Vegas","San Jacinto de Buena Fe","Las Vegas","Inundación / lluvias intensas + socavamiento","Alto","Alto",6,"población, viviendas, vías y energía",-0.893898,-79.496768],
["BF-06","Lot. Estela Espinoza","San Jacinto de Buena Fe","Lot. Estela Espinoza","Socavamiento","Alto","Alto",3,"población y viviendas",-0.886733,-79.487579],
["BF-07","El Cortijo - Nueva Buena Fe","11 de Octubre","El Cortijo, cerca del Mirador","Socavamiento","Alto","Alto",16,"población, viviendas, vías y energía",-0.889167,-79.4814],
["BF-08","Cooperativa Nogales Izurieta","San Jacinto de Buena Fe","A 5 cuadras del restaurante El Guayabal","Inundación / lluvias intensas","Medio","Medio",24,"población, viviendas y educación",-0.876635,-79.491315],
["BF-09","Las Margaritas","7 de Agosto","Atrás de la cancha de cemento","Socavamiento","Alto","Alto",60,"población, viviendas, vías, agua y energía",-0.874023,-79.493782],
["BF-10","13 de Marzo","7 de Agosto","Sector 13 de Marzo, vía a Platos","Inundación / lluvias intensas + socavamiento","Alto","Alto",50,"población, viviendas, vías y energía",-0.874054,-79.495909],
["BF-11","Nueva Esperanza","7 de Agosto","Antigua escuela Holger Echeverría, área comunal","Inundación / lluvias intensas + socavamiento","Alto","Alto",120,"población, viviendas, vías, educación, agua y energía",-0.873217,-79.48612],
["BF-12","Altos del Puerto Bajaña","11 de Octubre","Nueva Buena Fe","Socavamiento","Alto","Alto",28,"población, viviendas, vías, agua y energía",-0.887814,-79.482204],
["BF-13","Sector 7 - Patricia Pilar","Patricia Pilar","Entrada al cementerio","Inundación / lluvias intensas + socavamiento","Alto","Alto",50,"población, viviendas, vías, educación, agua y energía",-0.576483,-79.36919],
["BF-14","Lot. Ideal","San Jacinto de Buena Fe","La Ideal, cerca del Centro de Salud Tipo C","Inundación / lluvias intensas","Medio","Medio",24,"viviendas, salud, agua, energía y otros",-0.9052,-79.493676]
].map((r,i)=>({id:`ENOS-${r[0]}`,nombre:r[1],territorio:"TER-LOS-RIOS-BUENA-FE",parroquia:r[2],direccion:r[3],amenaza:r[4],nivel:r[5],prioridadPlan:r[6],poblacionExpuesta:r[7],elementosExpuestos:r[8],latitud:r[9],longitud:r[10],estado:"Pendiente de validación territorial",facilidadSolucion:"Por evaluar",brechaPrincipal:"Por determinar",brechas:"La brecha específica debe validarse en territorio y vincularse con las acciones F04.",descripcion:`${r[7]} personas expuestas; elementos expuestos: ${r[8]}.`,fechaRegistro:"2026-02-10",origen:"Plan ENOS",fuentePlan:"Plan Acciones FENOMENO DEL NIÑO 2026-2027 Cantón Buena Fe",fuentePagina:i<8?95:96,importacionId:"ENOS-2026-2027-PILOTO-01"})).concat([{
id:"ENOS-BALZAR-01",nombre:"Rcto. San Juan del Cerrito - puente vía E48",territorio:"TER-GUAYAS-BALZAR",parroquia:"Balzar",direccion:"Recinto San Juan del Cerrito, puente y vía E48",amenaza:"Inundación / anegamiento",nivel:"Alto",prioridadPlan:"Alto",poblacionExpuesta:200,viviendasExpuestas:50,elementosExpuestos:"población, viviendas, puente y vía E48",latitud:-1.46467,longitud:-79.921718,estado:"Pendiente de validación territorial",facilidadSolucion:"Media",brechaPrincipal:"Infraestructura",brechas:"Drenaje insuficiente, mantenimiento limitado y obras de mitigación inadecuadas o inexistentes.",descripcion:"Afectación potencial por desbordamiento del río Daule y estero San Juan. Aproximadamente 200 personas y 50 viviendas expuestas.",medidaNecesaria:"Mejorar drenaje, mantenimiento y definir obras de mitigación para proteger viviendas y conectividad vial.",fechaRegistro:"2026-07-18",origen:"Plan ENOS",fuentePlan:"Plan de Acción ENOS 2026-2027 del cantón Balzar",fuentePagina:8,importacionId:"ENOS-2026-2027-PILOTO-01"}])};
