window.F03_CARTOGRAPHY=[
  {
    "id": "MOCACHE-ENOS-2026-001|F03-CARTO-1",
    "parentIndex": 1,
    "provincia": "Los Ríos",
    "canton": "Mocache",
    "institucion": "GAD Mocache",
    "codigoCaso": "MOCACHE-ENOS-2026-001",
    "fechaRegistro": "2026-06-09",
    "tipo": "Mapa PDF / imagen",
    "formato": "PDF",
    "nombre": "Polígonos de zona afectada",
    "descripcion": "",
    "fuente": "GAD Mocache",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "SNGR-CZ5GR-2026-0312-O-10_59_46.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/775407597/attachments/attAkdasbAtXEjVXykshNqu5/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "Escala 1:50,000\nFecha: junio 2025\nCobertura completa"
  },
  {
    "id": "Cgrpalenque_ENOS_2026_001|F03-CARTO-1",
    "parentIndex": 2,
    "provincia": "Los Ríos",
    "canton": "Palenque",
    "institucion": "Gad Municipal de Palenque",
    "codigoCaso": "Cgrpalenque_ENOS_2026_001",
    "fechaRegistro": "2026-06-09",
    "tipo": "Croquis / mapa referencial",
    "formato": "Imagen JPG/PNG",
    "nombre": "Croquis/mapa referencial",
    "descripcion": "",
    "fuente": "Gad Municipal de Palenque",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "IMG-20260608-WA0126-11_2_9.jpg",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/775411206/attachments/atty8v3S7YyDsK3UnXdfkRPy/",
    "mapaUrl": "N/G",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "10/06/2026"
  },
  {
    "id": "Gad Montalvo 003-2026|F03-CARTO-1",
    "parentIndex": 3,
    "provincia": "Los Ríos",
    "canton": "Montalvo",
    "institucion": "Gad Montalvo",
    "codigoCaso": "Gad Montalvo 003-2026",
    "fechaRegistro": "2026-06-09",
    "tipo": "Croquis / mapa referencial",
    "formato": "PDF",
    "nombre": "Inundaciom",
    "descripcion": "",
    "fuente": "Gad Montalvo",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "LISSIA-11_14_54.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/775420373/attachments/attsZ9UsmoTc4YVgeaBvtjPN/",
    "mapaUrl": "Nim",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "Ninguna"
  },
  {
    "id": "GADCARACOL-ENOS-2026-001|F03-CARTO-1",
    "parentIndex": 4,
    "provincia": "Los Ríos",
    "canton": "Babahoyo",
    "institucion": "Gad Parroquial Caracol",
    "codigoCaso": "GADCARACOL-ENOS-2026-001",
    "fechaRegistro": "2026-06-09",
    "tipo": "Croquis / mapa referencial",
    "formato": "PDF",
    "nombre": "Mapas",
    "descripcion": "",
    "fuente": "Gad Babahoyo",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "SIN LIMITACIONES CONOCIDAS"
  },
  {
    "id": "GADMELEMPALME_ENOS_2026_001|F03-CARTO-1",
    "parentIndex": 5,
    "provincia": "Guayas",
    "canton": "El Empalme",
    "institucion": "GAD Municipal El Empalme",
    "codigoCaso": "GADMELEMPALME_ENOS_2026_001",
    "fechaRegistro": "2026-06-09",
    "tipo": "Mapa PDF / imagen",
    "formato": "Imagen JPG/PNG",
    "nombre": "Mapa de susceptibilidad a inundación, deslizamiento",
    "descripcion": "",
    "fuente": "GAD Municipal El Empalme",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "Mapas El Empalme-11_53_48.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/775457167/attachments/attJfDeHwtFpZxmhek8kkVFi/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "La principal limitación del insumo corresponde a la escala cartográfica utilizada (1:1500) actualizada en el año 2020, la cual, si bien permite una aproximación detallada a nivel local, puede no representar con precisión absoluta las microvariaciones del terreno ni las condiciones puntuales de cada predio. En este sentido, la información generada debe considerarse como referencial para la identificación de amenazas de inundación y deslizamiento, siendo necesario complementarla con levantamientos topográficos y estudios técnicos de mayor detalle para una evaluación más precisa del riesgo."
  },
  {
    "id": "Agrpalenque-ENOS-2026-001|F03-CARTO-1",
    "parentIndex": 6,
    "provincia": "Los Ríos",
    "canton": "Palenque",
    "institucion": "GAD Municipal de Palenque",
    "codigoCaso": "Agrpalenque-ENOS-2026-001",
    "fechaRegistro": "2026-06-11",
    "tipo": "Mapa PDF / imagen",
    "formato": "PDF",
    "nombre": "Mapa de susceptibilidad a inundacion.",
    "descripcion": "",
    "fuente": "GAD Municipal de palenque, Unidad de Avaluo y catastro.",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "Mapa de Zonas Susceptiblez a Inundaciones del Canton Palenque-9_10_37.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/777804608/attachments/attYqyTPsbG3wd2mtRpCwGUG/",
    "mapaUrl": "https://palenque.gob.ec/plan-de-desarrollo-yordenamiento-terriorial/",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "el análisis presentado se encuentra condicionado por la disponibilidad, escala y temporalidad de la información técnica utilizada para su elaboración."
  },
  {
    "id": "VINCESENOS-2026JCM001|F03-CARTO-1",
    "parentIndex": 7,
    "provincia": "Los Ríos",
    "canton": "Vinces",
    "institucion": "GAD Municipal del Cantón Vinces",
    "codigoCaso": "VINCESENOS-2026JCM001",
    "fechaRegistro": "2026-06-15",
    "tipo": "Mapa PDF / imagen",
    "formato": "Imagen JPG/PNG",
    "nombre": "Mapa de Riesgos ante Imundaciones",
    "descripcion": "",
    "fuente": "Universidad Estatal de Bolivar",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "INUNDACION-10_22_55.jpg",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/781242113/attachments/att8ooc8vrpiMjqAUYkfqFSA/",
    "mapaUrl": "No existe",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "Escala 1.62.500 (1cm - 625 metros). 20 de octubre del 2018. No existe reestrincuines de uso."
  },
  {
    "id": "VINCESENOS-2026JCM001|F03-CARTO-2",
    "parentIndex": 7,
    "provincia": "Los Ríos",
    "canton": "Vinces",
    "institucion": "GAD Municipal del Cantón Vinces",
    "codigoCaso": "VINCESENOS-2026JCM001",
    "fechaRegistro": "2026-06-15",
    "tipo": "Mapa PDF / imagen",
    "formato": "Imagen JPG/PNG",
    "nombre": "Mapa Hidrologico",
    "descripcion": "",
    "fuente": "Universidad Estatal de Bolivar",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "HIDROLOGICO-10_27_42.jpg",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/781242113/attachments/attNnSLrL2XVySZtFxV6d3Vh/",
    "mapaUrl": "No existe enlace",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "1:62.240 (1 cm - 622 metros) 19 de octubre del 2018, no existen reestrinciones para su uso."
  },
  {
    "id": "GAD MONTALVO 001 PLAN EMERGENCIA|F03-CARTO-1",
    "parentIndex": 8,
    "provincia": "Los Ríos",
    "canton": "Montalvo",
    "institucion": "GAD MUNICIPAL MONTALVO",
    "codigoCaso": "GAD MONTALVO 001 PLAN EMERGENCIA",
    "fechaRegistro": "2026-06-15",
    "tipo": "Mapa PDF / imagen",
    "formato": "Imagen JPG/PNG",
    "nombre": "VIAS RURALES",
    "descripcion": "",
    "fuente": "GAD MONTALVO",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "NINGUNA"
  },
  {
    "id": "GAD SALITRE-ENOS-2026-001|F03-CARTO-1",
    "parentIndex": 9,
    "provincia": "Guayas",
    "canton": "Salitre",
    "institucion": "GAD MUNICIPAL SALITRE",
    "codigoCaso": "GAD SALITRE-ENOS-2026-001",
    "fechaRegistro": "2026-06-15",
    "tipo": "Mapa PDF / imagen",
    "formato": "PDF",
    "nombre": "mapas",
    "descripcion": "",
    "fuente": "ordenamiento territorial",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "El AT ubicado en la cabecera cantonal de la provincia del Guayas, funciona principalmente como un centro multifuncional de acogida temporal para damnificados durante emergencias invernales y como un espacio de atención social comunitaria coordinado por el GAD Municipal"
  },
  {
    "id": "GAD-MPBV-001|F03-CARTO-1",
    "parentIndex": 10,
    "provincia": "Los Ríos",
    "canton": "Puebloviejo",
    "institucion": "GAD MUNICIPAL DE PUEBLOVIEJO",
    "codigoCaso": "GAD-MPBV-001",
    "fechaRegistro": "2026-06-15",
    "tipo": "Mapa PDF / imagen",
    "formato": "PDF",
    "nombre": "Mapa referencial de puntos críticos por efectos de inundación del cantón Puebloviejo dado por la unidad de Avaluos y catastro",
    "descripcion": "",
    "fuente": "GAD Municipal del Cantón Puebloviejo – Unidad de Gestión de Riesgos",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "AMENAZAS NATURALES INUNDACION-15_16_31.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/781464704/attachments/attNWxkHNuPK6JyyLn348b5s/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "Información referencial levantada mediante inspecciones técnicas de campo; requiere actualización periódica según las condiciones de la temporada invernal y eventos hidrometeorológicos."
  },
  {
    "id": "BORRADOR_BALZAR_001|F03-CARTO-1",
    "parentIndex": 11,
    "provincia": "Guayas",
    "canton": "Balzar",
    "institucion": "GAD MUNICIPAL DE BALZAR",
    "codigoCaso": "BORRADOR_BALZAR_001",
    "fechaRegistro": "2026-06-15",
    "tipo": "KML / KMZ",
    "formato": "SHP comprimido ZIP",
    "nombre": "PROYECTO SAN JUAN DEL CERRTIO, INUNDACION POR CRECIMIENTO DEL RIO DAULE, DESBORDAMIENTO DEL ESTERO SAN JUAN Y PROBLEMAS DE AGNEGACION",
    "descripcion": "",
    "fuente": "Gad Municipal",
    "geometria": "",
    "punto": "",
    "poligono": "",
    "archivo": "Rcto San Juan del Cerrito-19_23_24.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/781528388/attachments/att8XfSnqnzbiQ4Z2GGX9kjf/",
    "mapaUrl": "arth.google.com/web/search/Balzar/@-1.46534359,-79.92020699,16.71603626a,4453.92727481d,35y,0h,0t,0r/data=CiwiJgokCYjFaLXSaTJAEYbFaLXSaTLAGQ3Bl5ZPNUhAIeDVkyuFL0nAQgIIATIpCicKJQohMW1FZ2ZGRFlZR0F2NnViWXFnSmlEaXlYVllicmxkQWVCIAE6AwoBMEICCABKCAjDx-q9AhAB",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "El insumo corresponde a una delimitación geoespacial de alcance puntual y su precisión depende de la calidad del archivo base y de la fecha de levantamiento de la información. No sustituye estudios topográficos o hidrológicos detallados y puede no reflejar cambios recientes en las condiciones del terreno, la infraestructura o el uso del suelo. Se recomienda complementar con verificaciones en campo y actualización periódica de la información."
  },
  {
    "id": "PTO-001",
    "parentIndex": 12,
    "provincia": "guayas",
    "canton": "PALESTINA",
    "institucion": "GAD PALESTINA",
    "codigoCaso": "F01-F07",
    "fechaRegistro": 46190,
    "tipo": "amenazas",
    "formato": "kml_kmz",
    "nombre": "PDOT-PUGS",
    "descripcion": "Zona correspondiente al cantón Palestina, provincia del Guayas. Se reporta como referencia territorial para identificar el área de intervención y facilitar la planificación de actividades dentro del proceso ENOS. Esta información debe utilizarse para ubicar acciones, realizar seguimiento en el territorio y apoyar la toma de decisiones en el plan de acción.",
    "fuente": "GAD",
    "geometria": "punto",
    "punto": "-1.701796 -79.889654 0 0",
    "poligono": "",
    "archivo": "29 SUSCEPTIBILIDAD A INUNDACIONES2-14_42_53.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/783873847/attachments/attFxjoCCchaQTWnm6GKyrmd/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "CANTON PALESTINA - PARROQUI PALESTINA - PROVINCIA DEL GUAYAS",
    "limitaciones": ""
  },
  {
    "id": "GAD VALENCIA_PLAN DE ACCIÓN 001",
    "parentIndex": 13,
    "provincia": "los_rios",
    "canton": "CANTÓN VALENCIA",
    "institucion": "GAD CANTÓN VALENCIA",
    "codigoCaso": "GAD VALENCIA_PLAN DE ACCIÓN 001",
    "fechaRegistro": 46190,
    "tipo": "vulnerabilidad",
    "formato": "pdf",
    "nombre": "RECINTO CHIPE",
    "descripcion": "ESTE SITIO ES CONSIDERADO VULNERABLE POR SU EXPOSICIÓN A INUNDACION",
    "fuente": "GAD CANTON VALENCIA",
    "geometria": "descripcion_sin_mapa",
    "punto": "-0.980157 -79.351801 0 0",
    "poligono": "",
    "archivo": "CHIPE 1-16_15_51.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/783917811/attachments/attHddRBgzVYW83AnYtFvNW2/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "RECINTO CHIPE",
    "limitaciones": ""
  },
  {
    "id": "UMGR2026",
    "parentIndex": 14,
    "provincia": "guayas",
    "canton": "PLAYAS",
    "institucion": "GAD MUNICIPAL DEL CANTON PLAYAS",
    "codigoCaso": "UMGR2026",
    "fechaRegistro": 46189,
    "tipo": "otro",
    "formato": "pdf",
    "nombre": "PLAYAS",
    "descripcion": "EL PLANO DEL CANTON PLAYAS CON SUS RESPECTIVOS LIMITES, COMUNAS Y BARRIOS EXISTENTES EN EL CANTON PLAYAS",
    "fuente": "GAD MUNICIPAL DEL CANTON PLAYAS",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.501041 -80.567386 0 0;-2.488693 -80.532792 0 0;-2.498297 -80.486004 0 0;-2.487471 -80.461229 0 0;-2.479925 -80.464598 0 0;-2.468338 -80.448798 0 0;-2.470739 -80.442921 0 0;-2.467577 -80.397282 0 0;-2.476227 -80.390076 0 0;-2.522457 -80.385762 0 0;-2.527259 -80.367068 0 0;-2.608201 -80.37197 0 0;-2.62535 -80.359683 0 0;-2.651356 -80.354212 0 0;-2.664835 -80.35995 0 0;-2.691615 -80.324204 0 0;-2.714048 -80.310172 0 0;-2.717401 -80.309085 0 0;-2.720907 -80.305526 0 0;-2.640976 -80.439451 0 0;-2.501041 -80.567386 0 0",
    "archivo": "PLANO PLAYAS CON LIMITESY BARRIOS-17_33_7.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/783952603/attachments/attQQPLu4dnbDgMRKCTyLDLp/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "por_definir",
    "comunidadSector": "PLAYAS",
    "limitaciones": ""
  },
  {
    "id": "GADBUENAFE-ENOS-2026-001",
    "parentIndex": 15,
    "provincia": "los_rios",
    "canton": "BUENA FE",
    "institucion": "GAD MUNICIPAL SAN JACINTO DE BUENA FE",
    "codigoCaso": "GADBUENAFE-ENOS-2026-001",
    "fechaRegistro": 46063,
    "tipo": "zonas_priorizadas",
    "formato": "shp_zip",
    "nombre": "BUENA FE",
    "descripcion": "MAPA DEL CANTON BUENA FE Y ALLI ESTAN TODOS LOS SECTORES MAS VULNERABLES",
    "fuente": "GAD BUENA FE",
    "geometria": "poligono",
    "punto": "-0.89351 -79.489665 0 0",
    "poligono": "-0.8902 -79.504281 0 0;-0.869185 -79.493547 0 0;-0.870252 -79.479841 0 0;-0.919647 -79.479442 0 0;-0.91999 -79.50833 0 0;-0.8902 -79.504281 0 0",
    "archivo": "ZONA DE RIESGO BUENA FE-9_35_39.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/784724955/attachments/attD22NbV2gaanf8j8gaaAhm/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "SAN JACINTO DE BUENA FE",
    "limitaciones": "escala 1:25.000 actualizado en febrero 2026"
  },
  {
    "id": "GADBUENAFE-ENOS-2026-001",
    "parentIndex": 15,
    "provincia": "los_rios",
    "canton": "BUENA FE",
    "institucion": "GAD MUNICIPAL SAN JACINTO DE BUENA FE",
    "codigoCaso": "GADBUENAFE-ENOS-2026-001",
    "fechaRegistro": 46063,
    "tipo": "zonas_priorizadas",
    "formato": "shp_zip",
    "nombre": "PATRICIA PILAR",
    "descripcion": "CENTRO POBLADO DE PATRICIA PILAR CON LAS ZONAS MAS VULNERABLES",
    "fuente": "GAD BUENA FE",
    "geometria": "punto",
    "punto": "-0.572491 -79.370375 0 0",
    "poligono": "",
    "archivo": "ZONA DE RIESGO PATRICIA PILAR-9_35_16.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/784724955/attachments/attE6tFqp7mF3dBtoSV8QW6x/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "PATRIA PILAR - CENTRO POBLADO",
    "limitaciones": "ESCALA 1:25.000 ACTUALIZADO EN FEBRERO 2026"
  },
  {
    "id": "F03-18",
    "parentIndex": 16,
    "provincia": "guayas",
    "canton": "GUAYAQUIL",
    "institucion": "Ministerio de Agricultura, Ganadería y Pesca",
    "codigoCaso": "GUAYAS-MTT6-2026-001",
    "fechaRegistro": 46191,
    "tipo": "uso_cobertura_suelo",
    "formato": "geopackage link_drive",
    "nombre": "PRODUCTORES EXPUESTOS",
    "descripcion": "PARA MITIGAR LOS EFECTOS DE LAS INUNDACIONES",
    "fuente": "MAGP",
    "geometria": "punto",
    "punto": "-2.179407 -79.905025 10 1",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "ZONAS AFECTADAS DE LA PROVINCIA GUAYAS",
    "limitaciones": "NAVEGACIÓN CON INTERNET"
  },
  {
    "id": "F03-19",
    "parentIndex": 17,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL",
    "codigoCaso": "Pedro_carbo_Enos",
    "fechaRegistro": 46191,
    "tipo": "infraestructura_esencial",
    "formato": "kml_kmz",
    "nombre": "Planta de Agua",
    "descripcion": "La planta Potabilizadora de Agua es un elemento esencial dentro del Cantón Pedro Carbo, debido que su funcionamiento esta inmerso dentro de un Servicio Basico, distribución de liquido vital",
    "fuente": "Coordinación de gestión de riesgos",
    "geometria": "archivo_enlace",
    "punto": "-1.81355 -80.241071 0 0",
    "poligono": "",
    "archivo": "Planta de agua-7_22_8.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/785891110/attachments/attKcM7kmQ7mk3PzWdmwwX6x/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Sector Fumisa",
    "limitaciones": "Información es preliminar debido que se cuenta con mapa"
  },
  {
    "id": "F03-20",
    "parentIndex": 17,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL",
    "codigoCaso": "Pedro_carbo_Enos",
    "fechaRegistro": 46191,
    "tipo": "elementos_expuestos",
    "formato": "kml_kmz xlsx_csv",
    "nombre": "Puentes Peatonales",
    "descripcion": "Son puentes que permiten que la ciudadania de la zona rural no se queden aislada",
    "fuente": "GAD MUNICIPAL",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.811755 -80.265251 0 0",
    "poligono": "",
    "archivo": "Puentes peatonales-7_49_41.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/785891110/attachments/attFpbTKPpERSe8f6tKkJmu8/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Zona Rural de Pedro Carbo",
    "limitaciones": "Los puentes son de cañas y hieros pero deben darle mantenimientos debido q los materiales cumplen su ciclo"
  },
  {
    "id": "F03-21",
    "parentIndex": 17,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL",
    "codigoCaso": "Pedro_carbo_Enos",
    "fechaRegistro": 46191,
    "tipo": "elementos_expuestos",
    "formato": "xlsx_csv",
    "nombre": "Puente Pedro Carbo",
    "descripcion": "El puentees fundamental porque esta en una arteria vial como es Manabi - Guayas",
    "fuente": "GAD  MUNICIPAL",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.822965 -80.228542 0 0",
    "poligono": "",
    "archivo": "Puentes Pedro Carbo-7_56_17.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/785891110/attachments/attztHSHF4zzoyexB8iq4gMH/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Cabecera Cantonal",
    "limitaciones": "se necesita validar información"
  },
  {
    "id": "F03-22",
    "parentIndex": 17,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL",
    "codigoCaso": "Pedro_carbo_Enos",
    "fechaRegistro": 46191,
    "tipo": "elementos_expuestos",
    "formato": "xlsx_csv",
    "nombre": "Puntos Criticos cabecera Cantonal",
    "descripcion": "Son sectores de la zona Urbana que esta expuesto a inundaciones",
    "fuente": "GAD MUNICIPAL DE PEDRO CARBO",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.815773 -80.237056 0 0",
    "poligono": "",
    "archivo": "Zona Critica 01-10_17_39.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/785891110/attachments/attikUnLPTXvqT2bcMYJSb5S/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Las Cucharas, Barrio Guayaquil, San Ramon, Calles milagros, sector El Oro, Santa Rosa, Santa Martha, Pedregal Sector Duran",
    "limitaciones": "Son sectores geograficamente bajo"
  },
  {
    "id": "GADGUARANDA-ENOS-2026 NEGROYACO",
    "parentIndex": 18,
    "provincia": "galapagos",
    "canton": "GUARANDA",
    "institucion": "GAD GUARANDA",
    "codigoCaso": "GADGUARANDA-ENOS-2026",
    "fechaRegistro": 45791,
    "tipo": "amenazas",
    "formato": "geometria_kobo shp_zip",
    "nombre": "SECTOR NEGROYACO, PIRCAPAMBA Y SAN LUIS DE PAMBIL",
    "descripcion": "DEBIDO AL DESLIZAMIENTO DEL SECTOR NEGROYACO QUE AFECTA A VIVIENDAS, VIAS, BIENES Y SERVICIOS, SE REQUIERE DE OBRAS DE MITIGACIÓN COMO EMBAULADOS, DRENES Y SUBDRENES MEDIDAS GEOTECNICAS",
    "fuente": "GAD CANTONAL",
    "geometria": "punto",
    "punto": "-1.576594 -78.998839 0 0",
    "poligono": "",
    "archivo": "Poligono de afect Negroyaco-11_45_2.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786017323/attachments/attV6WywpJD3QdgdYwWuRgiF/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "NEGROYACO, PIRCAPAMBA SIO SUQUIBI PARROQUIA SAN LUIS DE PAMBIL",
    "limitaciones": "poca difusion de la informacion"
  },
  {
    "id": "GADGUARANDA-ENOS-2026",
    "parentIndex": 18,
    "provincia": "galapagos",
    "canton": "GUARANDA",
    "institucion": "GAD GUARANDA",
    "codigoCaso": "GADGUARANDA-ENOS-2026",
    "fechaRegistro": 45791,
    "tipo": "amenazas",
    "formato": "shp_zip",
    "nombre": "PIRCAPAMBA",
    "descripcion": "EL SECTOR PIRCAPAMBA AFECTADO POR UN DESLIZAMIENTO QUE AFECTA 8 HAS, QUE SE REQUIERE DE LA IMPLEMENTACION DE MEDIDAS DE MITIGACION PARA ESTABILIZACION",
    "fuente": "GAD GUARANDA",
    "geometria": "punto",
    "punto": "-1.588227 -78.986498 0 0",
    "poligono": "",
    "archivo": "PIRCAPAMBA poligono-11_53_32.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786017323/attachments/attp26cZfmhK9m3srr37mMJ9/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "PIRCAPAMBA PARROQUIA VEINTIMILLA",
    "limitaciones": "POCA DIFUSIÓN"
  },
  {
    "id": "F03-25",
    "parentIndex": 19,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL DE PEDRO CARBO",
    "codigoCaso": "Pedro_Carbo_Enos",
    "fechaRegistro": 46192,
    "tipo": "infraestructura_esencial",
    "formato": "xlsx_csv",
    "nombre": "Planta de Agua",
    "descripcion": "En la planta de tratamiento de Agua Potable, se reporta porque es un elemento esencial para la población",
    "fuente": "GAD MUNICIAL",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.812884 -80.240424 0 0",
    "poligono": "",
    "archivo": "Planta de agua-13_39_35.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786123870/attachments/att6sB4jAzZK54YvHCtGWTNT/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Parroquia Pedro Carbo",
    "limitaciones": "Son Datos preliminar que no se han validado en plano cartografico"
  },
  {
    "id": "F03-26",
    "parentIndex": 19,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL DE PEDRO CARBO",
    "codigoCaso": "Pedro_Carbo_Enos",
    "fechaRegistro": 46192,
    "tipo": "infraestructura_esencial",
    "formato": "xlsx_csv",
    "nombre": "Puentes Pedro Carbo",
    "descripcion": "en la parte lateral del puente se encuentra un socavamiento",
    "fuente": "GAD MUNICIPAL",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.822958 -80.228589 0 0",
    "poligono": "",
    "archivo": "Puentes Pedro Carbo-13_46_30.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786123870/attachments/attj3MPZ5wdxM9jDjMtfLhng/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Entrada a Pedro Carbo ante de llegar al GAD Municipal",
    "limitaciones": "Cantonal"
  },
  {
    "id": "F03-27",
    "parentIndex": 19,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL DE PEDRO CARBO",
    "codigoCaso": "Pedro_Carbo_Enos",
    "fechaRegistro": 46192,
    "tipo": "elementos_expuestos",
    "formato": "xlsx_csv",
    "nombre": "Puentes peatonales",
    "descripcion": "Se menciona debido que son elemento esenciales, porque la ciudadania transita en tiempo de invierno cuando los rios crecen",
    "fuente": "GAD MUNIICPAL",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.806983 -80.301461 0 0",
    "poligono": "",
    "archivo": "Puentes peatonales-13_50_19.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786123870/attachments/attHjkLLaaWJkwLbu5xw9svd/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Zona Rural",
    "limitaciones": "Son puentes peatonales que están dentro de la zona rural"
  },
  {
    "id": "F03-28",
    "parentIndex": 19,
    "provincia": "guayas",
    "canton": "Pedro Carbo",
    "institucion": "GAD MUNICIPAL DE PEDRO CARBO",
    "codigoCaso": "Pedro_Carbo_Enos",
    "fechaRegistro": 46192,
    "tipo": "amenazas",
    "formato": "xlsx_csv",
    "nombre": "Cabecera Cantonal pinto critico",
    "descripcion": "Son zonas critica donde las familias se inudan varios sectores",
    "fuente": "GAD MUNICIPAL",
    "geometria": "descripcion_sin_mapa",
    "punto": "-1.816791 -80.238447 0 0",
    "poligono": "",
    "archivo": "Zona Critica 01-14_11_8.xlsx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786123870/attachments/attcP4R8bAjCzobKSybsB2ud/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Cabecera Cantonal zona critica",
    "limitaciones": "se requiere validar los datos mediante un archivo cartogrfico"
  },
  {
    "id": "F03-29",
    "parentIndex": 20,
    "provincia": "guayas",
    "canton": "Daule",
    "institucion": "GAD Municipal Daule",
    "codigoCaso": "GADDAULE-ENOS-2026-001BORRADOR",
    "fechaRegistro": 46190,
    "tipo": "amenazas",
    "formato": "kml_kmz",
    "nombre": "Zona de Inundacion",
    "descripcion": "Recintos afectados durante la época lluviosa",
    "fuente": "GAD",
    "geometria": "poligono",
    "punto": "-1.841671 -79.96681 0 0",
    "poligono": "-1.825189 -79.955801 0.1 0.1;-1.826841 -79.933786 0.1 0.1;-1.837253 -79.934129 0 0;-1.864839 -79.98208 0 88;-1.825189 -79.955801 0.1 0.1",
    "archivo": "RIESGOS_ayuda_humanitaria-12_36_30.kmz",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/786158404/attachments/attVTq9gswrnwvukRZBkSKMo/",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Canton Daule",
    "limitaciones": "Ninguna"
  },
  {
    "id": "F03-30",
    "parentIndex": 21,
    "provincia": "guayas",
    "canton": "Cantón Naranjal",
    "institucion": "GAD Municipal del Cantón Naranjal",
    "codigoCaso": "GADNARANJAL-ENOS-2026-001",
    "fechaRegistro": 45988,
    "tipo": "amenazas",
    "formato": "pdf",
    "nombre": "Recintos y ciudadelas en zonas de inundación y movimiento de masa",
    "descripcion": "En el mapa de susceptibilidad de movimiento de masa y en el mapa de inundaciones, se encuentra detallado el nivel de riesgo en todo el cantón Naranjal; así mismo, se visualiza donde están asentados todos los recintos y ciudadelas, pudiendo identificar el nivel de riesgo que mantienen estos, ante los eventos mencionados.",
    "fuente": "División Política Administrativa del Ecuador (2021); GAD Municipal del Cantón Naranjal (2020); IGM (2018); PDOT (2025)",
    "geometria": "archivo_enlace",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "Todos los recintos del cantón Naranjal",
    "limitaciones": ""
  },
  {
    "id": "F03-31",
    "parentIndex": 21,
    "provincia": "guayas",
    "canton": "Cantón Naranjal",
    "institucion": "GAD Municipal del Cantón Naranjal",
    "codigoCaso": "GADNARANJAL-ENOS-2026-001",
    "fechaRegistro": 45988,
    "tipo": "vulnerabilidad",
    "formato": "pdf",
    "nombre": "Susceptibilidad de movimiento de masa e inundación",
    "descripcion": "En los mapas adjuntos, se observa el nivel de riesgo de susceptibilidad de masas y susceptibilidad de inundación, desglosado por las 5 parroquias del cantón Naranjal. Importante para conocer las parroquias con mayor incidencia a estos riesgos.",
    "fuente": "División Política Administrativa del Ecuador (2021); GAD Municipal del Cantón Naranjal (2020); IGM (2018); PDOT (2025)",
    "geometria": "archivo_enlace",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "Corresponde a todo el cantón Naranjal",
    "limitaciones": ""
  },
  {
    "id": "F03-32",
    "parentIndex": 21,
    "provincia": "guayas",
    "canton": "Cantón Naranjal",
    "institucion": "GAD Municipal del Cantón Naranjal",
    "codigoCaso": "GADNARANJAL-ENOS-2026-001",
    "fechaRegistro": 45988,
    "tipo": "hidrografia_drenaje",
    "formato": "pdf",
    "nombre": "Mapa hidrológico de Naranjal",
    "descripcion": "Principales afluentes que se encuentran dentro del perímetro de Naranjal, sirve para conocer los sectores cercanos a afluentes que pueden ser causante de desbordamiento.",
    "fuente": "División Política Administrativa del Ecuador (2021); GAD Municipal del Cantón Naranjal (2020); IGM (2018); PDOT (2025)",
    "geometria": "archivo_enlace",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "Todo el cantón Naranjal",
    "limitaciones": ""
  },
  {
    "id": "F03-33",
    "parentIndex": 21,
    "provincia": "guayas",
    "canton": "Cantón Naranjal",
    "institucion": "GAD Municipal del Cantón Naranjal",
    "codigoCaso": "GADNARANJAL-ENOS-2026-001",
    "fechaRegistro": 45988,
    "tipo": "relieve_pendientes",
    "formato": "pdf",
    "nombre": "Relieve y circunscripción territorial del cantón Naranjal",
    "descripcion": "Mapas que denotan la clasificación del relieve, mesorelieve, macrorelieve, mismos que se relacionan con la susceptibilidad de diferentes eventos, por la topografía de la zona.",
    "fuente": "División Política Administrativa del Ecuador (2021); GAD Municipal del Cantón Naranjal (2020); IGM (2018); PDOT (2025)",
    "geometria": "archivo_enlace",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "Todo el cantón Naranjal",
    "limitaciones": ""
  },
  {
    "id": "F03-34",
    "parentIndex": 21,
    "provincia": "guayas",
    "canton": "Cantón Naranjal",
    "institucion": "GAD Municipal del Cantón Naranjal",
    "codigoCaso": "GADNARANJAL-ENOS-2026-001",
    "fechaRegistro": 45988,
    "tipo": "uso_cobertura_suelo",
    "formato": "pdf",
    "nombre": "Cobertura de uso de suelo",
    "descripcion": "Mapa de uso y cobertura de suelo, además de su vulnerabilidad. La ocupación del territorio condiciona directamente el impacto socioeconómico del Fenómeno de El Niño, ya que determina qué sectores e infraestructuras estratégicas se encuentran expuestos a pérdidas por inundación o degradación física del suelo.",
    "fuente": "División Política Administrativa del Ecuador (2021); GAD Municipal del Cantón Naranjal (2020); IGM (2018); PDOT (2025)",
    "geometria": "archivo_enlace",
    "punto": "",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "media",
    "comunidadSector": "Todo el cantón Naranjal",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_CZ5_SNGR_ZONAL_GAD_MUNICIPAL_2026-F03-01",
    "parentIndex": 22,
    "provincia": "",
    "canton": "",
    "institucion": "GAD_MUNICIPAL",
    "codigoCaso": "ENOS_Z5_CZ5_SNGR_ZONAL_GAD_MUNICIPAL_2026",
    "fechaRegistro": 46193,
    "tipo": "",
    "formato": "",
    "nombre": "Sector Valdivia",
    "descripcion": "poligono que cubre el área de viviendas en el reciento",
    "fuente": "CZ5GR",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-1.802696 -80.001699 0 0;-1.802611 -79.99987 0 0;-1.803318 -79.997748 0 0;-1.804618 -79.996654 0 0;-1.805905 -79.995842 0 0;-1.806107 -79.99635 0 0;-1.805099 -79.997016 0 0;-1.804091 -79.998025 0 0;-1.803104 -80.001053 0 0;-1.80304 -80.001611 0 0;-1.802696 -80.001699 0 0",
    "archivo": "PROMPT_VIDEO_ENOS_ZONAL_5_GUIA_USO-16_44_8.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/787534076/attachments/attXH7cfiaDtz79nQDx5cuB4/",
    "mapaUrl": "",
    "calidad": "100",
    "estadoCalidad": "completa",
    "estadoValidacion": "reportado",
    "amenaza": "poblacion",
    "prioridad": "alta",
    "comunidadSector": "Valdivia- limonal- Daule",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_CZ5_SNGR_ZONAL_SNGR_CZ5_2026-F03-01",
    "parentIndex": 23,
    "provincia": "",
    "canton": "",
    "institucion": "SNGR_CZ5",
    "codigoCaso": "ENOS_Z5_CZ5_SNGR_ZONAL_SNGR_CZ5_2026",
    "fechaRegistro": 46194,
    "tipo": "",
    "formato": "",
    "nombre": "la casita",
    "descripcion": "la casita se inunda a un metro de profundidad",
    "fuente": "de la casita que se inunda",
    "geometria": "punto",
    "punto": "-1.406109 -75.44247 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "67",
    "estadoCalidad": "observado",
    "estadoValidacion": "reportado",
    "amenaza": "erosion_socavacion",
    "prioridad": "alta",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "F03-37",
    "parentIndex": 25,
    "provincia": "santa_elena",
    "canton": "Salinas",
    "institucion": "GAD Municipal de Salinas",
    "codigoCaso": "GADSALINAS_PAENOS_2026_2027",
    "fechaRegistro": 46195,
    "tipo": "amenazas",
    "formato": "sin_archivo",
    "nombre": "Talud parroquia Anconcito",
    "descripcion": "En el sector 9 de Octubre de la parroquia Anconcito, debido a la etapa invernal y a la erosion costera, hubo un deslizamiento de masa, provocando que el malecón 'Las fragatas' y parte de la vía se vea afectada.",
    "fuente": "GAD Municipal de Salinas",
    "geometria": "poligono",
    "punto": "-2.326921 -80.889153 0 0",
    "poligono": "-2.327088 -80.889287 0 0;-2.327422 -80.889029 0 0;-2.325954 -80.888632 0 0;-2.325804 -80.888385 0 0;-2.32573 -80.888523 0 0;-2.325964 -80.888819 0 0;-2.326549 -80.889049 0 0;-2.326867 -80.889402 0 0;-2.327072 -80.889244 0 0;-2.327056 -80.889212 0 0;-2.327088 -80.889287 0 0",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "Parroquia Anconcito",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026-PRELIM-F03-223607af-768a-4aa2-b963-e61e4ef966c1-1",
    "parentIndex": 26,
    "provincia": "BOLIVAR",
    "canton": "LAS_NAVES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "IMAGEN CARTOGRAMA RIO SUQUII",
    "descripcion": "EN LA IMAGEN PODEMOS OBSERVAR LA PERDIDA DE LOS TALUDES EN LA ZONA URBANA DEL CANTON LAS NAVES A LO LARGO DE LA CALLE DOMINGO GUEVARA",
    "fuente": "cartografia",
    "geometria": "punto",
    "punto": "-1.285318 -79.317785 0 0",
    "poligono": "",
    "archivo": "CARTOGRAMA 1-16_7_17.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/788739201/attachments/attP8cQaZYB9ZjQ5BVpGpefQ/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026-PRELIM-F03-223607af-768a-4aa2-b963-e61e4ef966c1-2",
    "parentIndex": 26,
    "provincia": "BOLIVAR",
    "canton": "LAS_NAVES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "mapa_amenaza",
    "formato": "shp_zip",
    "nombre": "MAPA MUROS DE CONCRETO RIO NAVES CHICO MALECON",
    "descripcion": "DAÑOS EN LOS MUROS DE CONCRETO DEL MALECON DEL RIO NAVES CHICO",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.287037 -79.316862 0 0",
    "poligono": "",
    "archivo": "CARTOGRAMA RIO NAVES CHICO-16_18_3.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/788739201/attachments/attKMj9ixANUYcsXzGZDZFvN/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026-PRELIM-F03-223607af-768a-4aa2-b963-e61e4ef966c1-3",
    "parentIndex": 26,
    "provincia": "BOLIVAR",
    "canton": "LAS_NAVES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "mapa_amenaza",
    "formato": "shp_zip",
    "nombre": "muros de gabiones calle 8 de diciembre rio naves chico",
    "descripcion": "los daños en los muros de gabiones del rio naves chico calle 8 de diiembre",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.287753 -79.31369 0 0",
    "poligono": "",
    "archivo": "imagen 3-16_50_3.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/788739201/attachments/attrx4BR2uYZHu2vrcM9Jhgt/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026-PRELIM-F03-223607af-768a-4aa2-b963-e61e4ef966c1-4",
    "parentIndex": 26,
    "provincia": "BOLIVAR",
    "canton": "LAS_NAVES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "pdf",
    "formato": "shp_zip",
    "nombre": "mapa la playita",
    "descripcion": "el daño en  mjuros de gabiones sector la playita produce desbordamiento del rio suquibi",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.289567 -79.326067 0 0",
    "poligono": "",
    "archivo": "IMAGEN 4-17_0_16.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/788739201/attachments/atta8TZYQzRY2jbygDJWZ4vd/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026-PRELIM-F03-223607af-768a-4aa2-b963-e61e4ef966c1-5",
    "parentIndex": 26,
    "provincia": "BOLIVAR",
    "canton": "LAS_NAVES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_LAS_NAVES_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "mapa_amenaza",
    "formato": "shp_zip",
    "nombre": "VIA LAS NAVES QUINSALOMA",
    "descripcion": "MUESTRA LOS POSIBLES DAÑOS POR LA PERDIDA DE TALUDES EN LA VIA LAS NAVES QUINSALOMA RIO UMBE",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.210691 -79.310807 0 0",
    "poligono": "",
    "archivo": "IMAGEN 5-17_9_36.zip",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/788739201/attachments/attbg4hzMPsjGVY9wwteebjY/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_PLAYAS_GAD_2026-PRELIM-F03-7cd55036-d8c1-40bd-b9de-83e3b44696fb-1",
    "parentIndex": 27,
    "provincia": "GUAYAS",
    "canton": "PLAYAS",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_PLAYAS_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "mapa_riesgo",
    "formato": "pdf",
    "nombre": "Mapa de Playas",
    "descripcion": "Esta basad en la información obtenida en las inudaciones del año 2024",
    "fuente": "campo",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.626271 -80.382754 0 0;-2.624214 -80.384732 0 0;-2.627986 -80.389627 0 0;-2.630901 -80.383902 0 0;-2.642476 -80.376751 0 0;-2.641447 -80.37323 0 0;-2.635188 -80.374171 0 0;-2.63133 -80.378463 0 0;-2.631073 -80.380008 0 0;-2.63073 -80.382331 0 0;-2.626271 -80.382754 0 0",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "El mapa fue elaborado con el personal tecnico de la Secretaría de gestión de Riesgos, el Instituto Geofisico militar y tecnicos de la unidad de gestión de riesgos."
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_BOLIVAR_PREFECTURA_2026-PRELIM-F03-0d623508-c158-4645-8537-363adbbc9a23-1",
    "parentIndex": 28,
    "provincia": "BOLIVAR",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_BOLIVAR_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_amenaza",
    "formato": "imagen",
    "nombre": "GOOGLE",
    "descripcion": "En San Pablo Bajo, el peligro está representado por el aumento del caudal del río en época invernal, lo que genera riesgo de desbordamientos e inundaciones que pueden afectar a la población, viviendas y vías de acceso.",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.959851 -79.191392 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026-PRELIM-F03-7da2e0df-30b2-4858-8283-7862e8ca534b-1",
    "parentIndex": 29,
    "provincia": "BOLIVAR",
    "canton": "CHILLANES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "pdf",
    "nombre": "Mapa de Deslizamientos",
    "descripcion": "Deslizamientos consttantes en el secotor La Margarita, suelo inestable",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.926257 -79.154331 0 0",
    "poligono": "",
    "archivo": "MAPA DE DESLIZAMIENTO-8_51_28.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/789554724/attachments/attfqgmMZYkfGR2RwqSkfyxc/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026-PRELIM-F03-e0bd9899-fc43-4e81-8fb7-d0bfb96e8440-1",
    "parentIndex": 30,
    "provincia": "BOLIVAR",
    "canton": "CHILLANES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_amenaza",
    "formato": "pdf",
    "nombre": "Mapa de desbordamientos rio dulcepamba",
    "descripcion": "Mapa por desbordamientos de rios",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.960036 -79.191364 0 0",
    "poligono": "",
    "archivo": "DESBORDAMIENTOS DE RIOS-9_30_5.docx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/789614704/attachments/attuKKUN47mK5yB9yudoiu7g/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_BOLIVAR_PREFECTURA_2026-PRELIM-F03-8cb386c0-8c38-4e93-b66c-e7e7dd8d2af3-1",
    "parentIndex": 31,
    "provincia": "BOLIVAR",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_BOLIVAR_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "otro",
    "formato": "imagen",
    "nombre": "Google",
    "descripcion": "La infraestructura del sector Dulcepamba (viviendas, vías y puentes) está expuesta al desbordamiento del río. Este fenómeno puede causar inundaciones, erosión y colapso de estructuras, aumentando el riesgo y la vulnerabilidad de la población.",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.941478 -79.17236 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026-PRELIM-F03-61615169-a4ab-4967-a9cc-11e986b07a58-1",
    "parentIndex": 32,
    "provincia": "SANTA_ELENA",
    "canton": "SALINAS",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "mapa_riesgo",
    "formato": "otro",
    "nombre": "Inundación sector San Raymundo II",
    "descripcion": "El sector San Raymundo II, parroquia José Luis Tamayo, cantón Salinas, es considerado una zona de riesgo alto ante inundaciones debido a que se encuentra en una cota baja respecto al paso lateral 'La Libertad-Salinas' y, además, existe colapso y rebose de aguas servidas.",
    "fuente": "gad",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.251836 -80.92969 0 0;-2.254066 -80.92941 0 0;-2.25368 -80.926877 0 0;-2.253026 -80.926437 0 0;-2.252705 -80.925847 0 0;-2.251911 -80.926115 0 0;-2.252061 -80.927092 0 0;-2.252158 -80.928144 0 0;-2.25159 -80.929163 0 0;-2.251836 -80.92969 0 0",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_COLIMES_GAD_2026-PRELIM-F03-166ee210-e37f-4a24-8f36-9dd150ab1438-1",
    "parentIndex": 33,
    "provincia": "GUAYAS",
    "canton": "COLIMES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_COLIMES_GAD_2026",
    "fechaRegistro": 46194,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "solo imagen",
    "descripcion": "Actualmente no se dispone de cartografía específica del área de intervención. Se considera factible y necesario que la Secretaría correspondiente, en coordinación con el Gobierno Autónomo Descentralizado Municipal de Colimes, apoye en la generación y actualización de información cartográfica que permita identificar con precisión la ubicación de las zonas vulnerables y las áreas potencialmente afectadas por inundaciones.  Esta información contribuirá al análisis del riesgo, la planificación de acciones de mitigación y la toma de decisiones para reducir la vulnerabilidad de la población y de la infraestructura expuesta a eventos adversos.",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.639002 -80.025574 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "Actualmente no se cuenta con una cartografía de riesgos del sector, lo que limita la identificación precisa de las áreas vulnerables y la planificación de medidas de prevención y mitigación. Se recomienda gestionar la elaboración y actualización de esta información cartográfica mediante el trabajo coordinado entre las instituciones competentes y el GAD Municipal de Colimes."
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026-PRELIM-F03-1469c184-6c9b-4592-a336-3f861ddbf300-1",
    "parentIndex": 34,
    "provincia": "BOLIVAR",
    "canton": "CHILLANES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_amenaza",
    "formato": "imagen",
    "nombre": "google maps",
    "descripcion": "El riesgo representa la probabilidad de que el río Changuil se desborde y cause daños en la parroquia San José del Tambo. Se relaciona directamente con la exposición de viviendas, vías y cultivos ubicados cerca del cauce, los cuales pueden verse afectados por inundaciones, erosión y arrastre de material.",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.954393 -79.232269 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026-PRELIM-F03-79ae9ec1-b395-4269-af1b-df2e0a954e3e-1",
    "parentIndex": 35,
    "provincia": "SANTA_ELENA",
    "canton": "SALINAS",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "otro",
    "nombre": "Inundación sector Nueva Jerusalén",
    "descripcion": "El sector Nueva Jerusalén, de la parroquia José Luis Tamayo, es considerado una zona inundable debido a que se encuentra en una cota baja respecto a la via paso lateral 'La Libertad - Santa Elena'",
    "fuente": "gad",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.256573 -80.917758 0 0;-2.253444 -80.918549 0 0;-2.254902 -80.915115 0 0;-2.255674 -80.91533 0 0;-2.256618 -80.916639 0 0;-2.257068 -80.917669 0 0;-2.256573 -80.917758 0 0",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026-PRELIM-F03-45c0cff0-3675-4a29-b502-244dc695adc9-1",
    "parentIndex": 36,
    "provincia": "SANTA_ELENA",
    "canton": "SALINAS",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "otro",
    "nombre": "Inundación sector Colinas de Salinas, parroquia José Luis Tamayo",
    "descripcion": "El sector Colinas de Salinas, parroquia José Luis Tamayo, del cantón Salinas, es considerado un sector susceptible a inundacion debido a que se encuentra en una cota baja respecto al paso lateral 'La Libertad - Santa Elena'",
    "fuente": "gad",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.257244 -80.917511 0 0;-2.256858 -80.917222 0 0;-2.256709 -80.916644 0 0;-2.257143 -80.916263 0 0;-2.256634 -80.915699 0 0;-2.256768 -80.915157 0 0;-2.256901 -80.914173 0 0;-2.257158 -80.91368 0 0;-2.258391 -80.913831 0 0;-2.259527 -80.913766 0 0;-2.260001 -80.914285 0 0;-2.257299 -80.917505 0 0;-2.257244 -80.917511 0 0",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026-PRELIM-F03-a771bdb4-33a7-4fb9-962c-e058f26177e6-1",
    "parentIndex": 37,
    "provincia": "SANTA_ELENA",
    "canton": "SALINAS",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_SANTA_ELENA_SALINAS_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "otro",
    "nombre": "Inundación vía Carlos Espinoza Larrea",
    "descripcion": "la vía Carlos Espinoza Larrea, en el sector Santa Paula específicamente, parroquia José Luis Tamayo, cantón Salinas, se inunda debido a que el sistema de alcantarilla colapsa, dificultando el paso de vehículos",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-2.228905 -80.926151 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-d2ab78fa-76d2-4d20-84c1-b8179b5dd485-1",
    "parentIndex": 38,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "San Vicente - Caracol",
    "descripcion": "Rotura de via por incremento del caudal",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.850085 -79.583073 0 0",
    "poligono": "",
    "archivo": "San Vicente  - Caracol-14_12_21.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/789970512/attachments/attEsdQXbjw729dvZJjM8Zey/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "F03-55",
    "parentIndex": 39,
    "provincia": "guayas",
    "canton": "Samborondón",
    "institucion": "Ilustre Municipalidad de la ciudad de Samborondón",
    "codigoCaso": "ENOS-Samborondon-001",
    "fechaRegistro": 45786,
    "tipo": "vulnerabilidad",
    "formato": "shp_zip",
    "nombre": "Susceptibilidad a inundaciones del cantón",
    "descripcion": "Insumo para generar mapa de zonas susceptibles a inundaciones en el cantón",
    "fuente": "IMCS",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.164638 -79.86503 0 0;-2.149383 -79.85069 0 0;-2.124315 -79.849138 0 0;-2.093803 -79.852413 0 0;-2.085385 -79.845776 0 0;-2.091561 -79.834778 0 0;-2.096364 -79.817254 0 0;-2.097051 -79.80489 0 0;-2.094306 -79.795318 0 0;-2.083327 -79.792873 0 0;-2.072782 -79.803613 0 0;-2.05501 -79.806557 0 0;-2.037855 -79.803089 0 0;-2.034423 -79.796215 0 0;-2.030992 -79.772153 0 0;-2.028934 -79.759103 0 0;-2.026875 -79.745361 0 0;-2.015896 -79.73712 0 0;-2.002857 -79.741937 0 0;-1.994623 -79.746749 0 0;-1.985198 -79.745891 0 0;-1.979365 -79.738676 0 0;-1.978084 -79.7274 0 0;-1.974064 -79.722418 0 0;-1.957766 -79.718804 0 0;-1.946277 -79.716312 0 0;-1.934268 -79.717363 0 0;-1.925689 -79.723873 0 0;-1.927405 -79.73244 0 0;-1.919513 -79.733512 0 0;-1.914709 -79.743456 0 0;-1.909219 -79.755132 0 0;-1.907752 -79.759601 0 0;-1.9027 -79.766453 0 0;-1.909905 -79.770591 0 0;-1.920874 -79.79096 0 0;-1.914012 -79.803311 0 0;-1.905776 -79.815664 0 0;-1.904404 -79.829382 0 0;-1.889992 -79.848634 0 0;-1.903031 -79.854146 0 0;-1.936658 -79.845871 0 0;-1.959991 -79.835939 0 0;-2.005968 -79.829735 0 0;-2.019693 -79.854113 0 0;-2.033245 -79.868537 0 0;-2.048514 -79.870602 0 0;-2.059699 -79.873959 0 0;-2.061757 -79.884947 0 0;-2.074315 -79.894495 0 0;-2.106977 -79.884043 0 0;-2.134836 -79.877365 0 0;-2.156656 -79.871773 0 0;-2.164638 -79.86503 0 0",
    "archivo": "Z_SUSCEP_INUND-14_7_7.zip",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-567cdff1-1724-4306-9c33-7cc4048c87d4-1",
    "parentIndex": 40,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "Salampe - Ricaurte",
    "descripcion": "Asolvamiento del rio y sus muros rotos que no contiene sus aguas en su cauce",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.538965 -79.466427 0 0",
    "poligono": "",
    "archivo": "Salampe- Ricaurte-14_43_15.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/789998379/attachments/attsyb4JMSkyzjoVpoBtqGEp/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_COLIMES_GAD_2026-PRELIM-F03-7f0b718f-aeaa-45f3-837e-b1f2668bc2e5-1",
    "parentIndex": 41,
    "provincia": "GUAYAS",
    "canton": "COLIMES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_COLIMES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "fotografia",
    "descripcion": "Su relación con la gestión del riesgo es fundamental, ya que facilita la planificación territorial, la toma de decisiones para la prevención y mitigación de desastres, la elaboración de planes de emergencia y evacuación, así como la priorización de acciones y recursos destinados a reducir los impactos de las inundaciones sobre la población y sus bienes. Por ello, el cantón Colimes y sus parroquias requieren contar con una cartografía zonificada de inundaciones actualizada que permita fortalecer la gestión integral del riesgo de desastres.",
    "fuente": "informe",
    "geometria": "punto",
    "punto": "-1.638356 -80.024843 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-99d3286d-2ea4-4f83-956d-eaaee5eef3d8-1",
    "parentIndex": 42,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "La Lucha Febres cordeo",
    "descripcion": "socavon en la via por Hundimiento en Alcantarilla",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.885703 -79.430614 0 0",
    "poligono": "",
    "archivo": "La Lucha Febres Cordero-15_23_22.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790028291/attachments/attGXy4zW9VnF2kzXxDARLg9/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-970c36ec-ae66-4708-b4c3-bc123fd955c6-1",
    "parentIndex": 43,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "San Antonio Bajo",
    "descripcion": "Socavon en alcantarilla de via lastrada",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.746418 -79.279547 0 0",
    "poligono": "",
    "archivo": "San Antonio Bajo-15_50_47.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790045374/attachments/attaVRSN4d3P5FQNxZssz9Rr/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_QUEVEDO_GAD_2026-PRELIM-F03-63e37d38-7d6b-4b2f-afd7-9893bd556523-1",
    "parentIndex": 44,
    "provincia": "LOS_RIOS",
    "canton": "QUEVEDO",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_QUEVEDO_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "MAPA DE SUSCEPTIBILIDAD A INUNDACIONES",
    "descripcion": "Sectores susceptibles a inundaciones, familias vulnerables a desbordamiento del rio Quevedo",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-1.042549 -79.462476 0 0",
    "poligono": "",
    "archivo": "MAPA SUSCEPTIBLE A INUNDACIONES-16_5_17.docx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790053886/attachments/att9CcRbytNJSHGNbKBKU4Hd/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-8d4360fe-8d65-4530-bf2c-30dcc5d52cd1-1",
    "parentIndex": 45,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "La Mona Via Tres Maria",
    "descripcion": "elevacion de muro en via y proteccion de puente",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.805201 -79.472754 0 0",
    "poligono": "",
    "archivo": "La Mona Via Tres Maria-16_21_31.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790061106/attachments/attJdskiWLQJemozodKxhv6o/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_MOCACHE_GAD_2026-PRELIM-F03-4ead523f-8f33-4406-a976-ada1abd1fd74-1",
    "parentIndex": 46,
    "provincia": "LOS_RIOS",
    "canton": "MOCACHE",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_MOCACHE_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "pdf",
    "nombre": "Mapa de Zona de Riesgo - Sector La Yuca",
    "descripcion": "Dentro de este mapa se identificaron las viviendas que se encuentran expuestas al fenómeno de inundación",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.252196 -79.526679 72 0",
    "poligono": "",
    "archivo": "ZONAS DE RIESGO LA YUCA-16_14_31.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790061240/attachments/att8aGtMPTDzGpvjWdJMcShY/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_MOCACHE_GAD_2026-PRELIM-F03-4ead523f-8f33-4406-a976-ada1abd1fd74-2",
    "parentIndex": 46,
    "provincia": "LOS_RIOS",
    "canton": "MOCACHE",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_MOCACHE_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "pdf",
    "nombre": "Mapa de Zona de Riesgos Sector Santa Barbara",
    "descripcion": "Dentro de este mapa se identificaron las viviendas que se encuentran expuestas al fenómeno de inundación",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.258453 -79.532231 0 0",
    "poligono": "",
    "archivo": "ZONAS DE RIESGO SANTA BARBARA-16_16_10.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790061240/attachments/att6WdPp8w6wq3w82nP9j4wc/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_MOCACHE_GAD_2026-PRELIM-F03-4ead523f-8f33-4406-a976-ada1abd1fd74-3",
    "parentIndex": 46,
    "provincia": "LOS_RIOS",
    "canton": "MOCACHE",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_LOS_RIOS_MOCACHE_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_riesgo",
    "formato": "pdf",
    "nombre": "Mapa de Zona de Riesgos Sector La Propicia",
    "descripcion": "Dentro de este mapa se identificaron las viviendas que se encuentran expuestas al fenómeno de inundación",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.264836 -79.535588 0 0",
    "poligono": "",
    "archivo": "ZONAS DE RIESGO LA PROPICIA-16_17_46.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790061240/attachments/att7WXQRwzYCWmdxU64kLXSL/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_COLIMES_GAD_2026-PRELIM-F03-31f87a0f-8b07-40c3-8a1d-5e8b2f25c7ba-1",
    "parentIndex": 47,
    "provincia": "GUAYAS",
    "canton": "COLIMES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_COLIMES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "Fotografías",
    "descripcion": "Actualmente, el cantón Colimes no cuenta con una cartografía específica de zonas de riesgo por inundación. Sin embargo, dispone de registros de evidencias mediante fotografías, inspecciones de campo e informes técnicos que identifican los sectores recurrentemente afectados por inundaciones durante la temporada invernal.",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.638543 -80.024908 0 0",
    "poligono": "",
    "archivo": "",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": "60",
    "estadoCalidad": "observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "mapa No 06 multiamenzasa",
    "parentIndex": 48,
    "provincia": "bolivar",
    "canton": "guaranda",
    "institucion": "gad guaranda",
    "codigoCaso": "GADGUARANDA-ENOS-2026",
    "fechaRegistro": 46063,
    "tipo": "amenazas",
    "formato": "geometria_kobo",
    "nombre": "mapa multiamenzasas de la ciudad de Guaranda",
    "descripcion": "Sector Negroyaco seslizamiento, sector pircapamba deslizamiento, san luis de pambil",
    "fuente": "gad guaranda",
    "geometria": "punto",
    "punto": "-1.576416 -78.999235 0 0",
    "poligono": "",
    "archivo": "2-16_51_1.png",
    "archivoUrl": "",
    "mapaUrl": "",
    "calidad": null,
    "estadoCalidad": "",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "alta",
    "comunidadSector": "negroyaco, pircapamba, san luis de pambil",
    "limitaciones": "recursos economicos"
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-acc74cfc-87e3-45ac-8169-d68805b2e5a1-1",
    "parentIndex": 49,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "El Saltadero - Febres Cordero",
    "descripcion": "Rotura de muro de proteccion que afecta a los moradores",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.895578 -79.252028 0 0",
    "poligono": "",
    "archivo": "El Saltadero - Febres Cordero-16_59_14.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/790080369/attachments/attXdCNyXGTPRWNAXGgr9wxE/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_SAN_MIGUEL_GAD_2026-PRELIM-F03-d6f7cc08-a758-4f01-9420-698247693048-1",
    "parentIndex": 50,
    "provincia": "BOLIVAR",
    "canton": "SAN_MIGUEL",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_SAN_MIGUEL_GAD_2026",
    "fechaRegistro": 46196,
    "tipo": "mapa_riesgo",
    "formato": "shp_zip",
    "nombre": "MAPA DE RIESGOS DEL CANTON SAN MIGULEL DE BOLIVAR",
    "descripcion": "Se adjunta el mapa de riesgos elaborado durante el proceso de actualización del Plan de Desarrollo y Ordenamiento Territorial (PDOT), con el apoyo de los consultores contratados para dicho proceso. El mapa identifica las zonas de amenaza y los elementos expuestos en el sector Chaupiyacu, permitiendo ubicar el área susceptible a aluviones y deslizamientos, así como las viviendas, locales comerciales y la infraestructura vial potencialmente afectadas. Esta información constituye un insumo técnico para la planificación, la gestión del riesgo y la priorización de medidas de prevención y mitigación.",
    "fuente": "cartografia",
    "geometria": "punto",
    "punto": "-1.709494 -79.041447 0 0",
    "poligono": "",
    "archivo": "MAPAS-12_0_32.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/791189731/attachments/att8U9F5bUFuZKr8apginHVz/",
    "mapaUrl": "https://drive.google.com/file/d/1FJnzPw_lZk9mQ-bHcSlTUf93-toA2ikv/view?usp=drive_link",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "El mapa de riesgos corresponde a la actualización del PDOT y constituye un insumo técnico referencial para la identificación de las zonas de amenaza en el sector Chaupiyacu. La información deberá complementarse y actualizarse periódicamente con inspecciones de campo y estudios técnicos específicos, considerando la dinámica de los eventos registrados durante las temporadas invernales."
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026-PRELIM-F03-53eb9a4d-33d6-4a29-b07b-c08781d55703-1",
    "parentIndex": 51,
    "provincia": "BOLIVAR",
    "canton": "CHILLANES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_amenaza",
    "formato": "pdf",
    "nombre": "DESBORDAMIENTOS DEL RIO DULCEPAMBA",
    "descripcion": "MAPA DE DESBORADAMIENTOS DEL RIO DULCEPAMBA PARROQUIA SAN JOSE DEL TAMBO QUE PERTENECE AL CANTON CHILLANES",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.960272 -79.191273 0 0",
    "poligono": "",
    "archivo": "DESBORDAMIENTOS DE RIOS-17_28_13.docx",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/791432254/attachments/attTdB8mEXn6CoM6KMdQ9SDD/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026-PRELIM-F03-53eb9a4d-33d6-4a29-b07b-c08781d55703-2",
    "parentIndex": 51,
    "provincia": "BOLIVAR",
    "canton": "CHILLANES",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_CHILLANES_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "mapa_amenaza",
    "formato": "pdf",
    "nombre": "MAPA DE DESLIZAMIENTOS DEL CANTON CHILLANES",
    "descripcion": "DESLIZAMIENTOS QUE AFECTAN A LAS VIAS DEL CANTON CHILLANES QUE HACEN CONEXION A LAS COMUNIDADES ALEDAÑAS",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.92517 -79.155285 0 0",
    "poligono": "",
    "archivo": "MAPA DE DESLIZAMIENTO-17_36_16.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/791432254/attachments/attyfE2uBpqJoJQMciVELT47/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_ECHEANDIA_GAD_2026-PRELIM-F03-7426d31e-204b-40f8-ac44-5030425fc6d2-1",
    "parentIndex": 52,
    "provincia": "BOLIVAR",
    "canton": "ECHEANDIA",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_BOLIVAR_ECHEANDIA_GAD_2026",
    "fechaRegistro": 46195,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "Mapa de suceptibilida as inundaciones",
    "descripcion": "mapas preliminares de amenaza por inundación de esta Cartera de Estado y partir de la geología y geomorfología observada en campo, el sector de San José de Camarón, se encuentra ubicado dentro del área de influencia de los ríos Camarón y Chazo Juan, presenta una baja susceptibilidad a inundaciones.",
    "fuente": "informe",
    "geometria": "punto",
    "punto": "-1.405231 -79.213053 0 0",
    "poligono": "",
    "archivo": "Mapa de Inundación Cmarón-21_48_8.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/791453834/attachments/attkayYPh9A9aU2BVsDynfWZ/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026-PRELIM-F03-e9cb7c53-44cb-46fe-9666-9799cf9d56d3-1",
    "parentIndex": 53,
    "provincia": "LOS_RIOS",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_PROVINCIAL_LOS_RIOS_PREFECTURA_2026",
    "fechaRegistro": 46196,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "San Vicente - Caracol",
    "descripcion": "El colapso de la plataforma de rodadura se relaciona con el riesgo porque es la manifestacionde la interaccion entre la amenaza puede estar representada por fenomenos como lluvias intensas, desbordamiento de rio, la exposicion corresponde a la via ubicada en zonas susceptibles a estos fenomenos",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-1.741322 -79.462332 0 0",
    "poligono": "",
    "archivo": "San Vicente - Caracol-21_43_56.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/791509515/attachments/attktpuQZYzqrTU6XqCXeMLT/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_LOMAS_DE_SARGENTILLO_GAD_2026-PRELIM-F03-eb5027e0-08eb-4a8c-84c9-e4fb7e3d8d39-1",
    "parentIndex": 54,
    "provincia": "GUAYAS",
    "canton": "LOMAS_DE_SARGENTILLO",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_LOMAS_DE_SARGENTILLO_GAD_2026",
    "fechaRegistro": 46197,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "Mapa PDF/Imagen",
    "descripcion": "Imagen y ubicación georreferenciada del puente carrozable del sector Mamey, donde se evidencian zonas susceptibles a inundación durante la temporada invernal, afectando la conectividad de las comunidades de Mamey, Caña Brava y Estero Loco.",
    "fuente": "campo",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-1.800518 -80.069089 0 0;-1.803005 -80.066729 0 0;-1.80041 -80.064926 0 0;-1.798287 -80.066428 0 0;-1.800518 -80.069089 0 0",
    "archivo": "Mapa de Inundaciones de Lomas de Sargentillo-14_12_21.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/792559984/attachments/att2uJh6vTYhiXS9Vh6hEPN9/",
    "mapaUrl": "no",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "La ubicación del sitio crítico fue identificada mediante inspección de campo y registro fotográfico. El área presenta antecedentes de inundaciones recurrentes durante la temporada invernal, afectando la conectividad de las comunidades aledañas."
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_NARANJITO_GAD_2026-PRELIM-F03-82d788a2-eb15-4451-a9ff-5926ef525dd3-1",
    "parentIndex": 55,
    "provincia": "GUAYAS",
    "canton": "NARANJITO",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_NARANJITO_GAD_2026",
    "fechaRegistro": 46197,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "Mapa cartográfico Siempre Vivas",
    "descripcion": "Se observa un territorio delimitado por polígonos, posiblemente parroquias, recintos o unidades administrativas.  Está representada una red de ríos y esteros principales, marcada en líneas azules, que atraviesan gran parte del área de estudio.   En varios tramos del sistema hídrico aparecen zonas resaltadas en color rojo, lo que sugiere:  •\tÁreas de riesgo por inundación,  •\tSectores con erosión o desbordamiento, o  •\tPuntos críticos identificados en el territorio.    El mapa incluye una flecha de orientación (Norte) en la parte superior izquierda.  En la parte inferior se observa una escala gráfica en metros, que permite estimar distancias (aprox. hasta 4.600 m).  El fondo del mapa utiliza diferentes tonos de color para diferenciar unidades territoriales o zonas de uso del suelo.",
    "fuente": "gad",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.101377 -79.449316 0 0;-2.101118 -79.44955 0 0;-2.101509 -79.449878 0 0;-2.101753 -79.449659 0 0;-2.101377 -79.449316 0 0",
    "archivo": "cartografia siempre vivas-13_50_4.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/792563899/attachments/attgEE4y6N6ymREc5BtpSACL/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_NARANJITO_GAD_2026-PRELIM-F03-82d788a2-eb15-4451-a9ff-5926ef525dd3-2",
    "parentIndex": 55,
    "provincia": "GUAYAS",
    "canton": "NARANJITO",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_NARANJITO_GAD_2026",
    "fechaRegistro": 46197,
    "tipo": "pdf",
    "formato": "pdf",
    "nombre": "La Unión inundación",
    "descripcion": ".Aportes específicos:  Identificación de Zonas de Amenaza: El mapa clasifica y georreferencia las distintas áreas del recinto según su nivel de exposición a inundaciones, permitiendo distinguir entre zonas de alto, medio y bajo riesgo.  Apoyo a la Planificación Territorial: Al señalar las áreas no aptas para ciertos usos (como la vivienda o infraestructura crítica), el mapa sirve como base para la toma de decisiones en la ordenación del suelo, evitando la ocupación de zonas peligrosas.  Herramienta para la Gestión de Emergencias: Facilita la elaboración de planes de evacuación, la ubicación de refugios temporales y la coordinación de rutas de acceso para los equipos de rescate, al conocer de antemano las vías y sectores que podrían quedar anegados.  Información para la Comunidad: Empodera a los habitantes del recinto \"La Unión\" con conocimiento objetivo sobre su entorno, fomentando una cultura de prevención y preparación ante posibles desastres naturales.  Referente para Estudios Técnicos: Sirve como insumo para ingenieros, urbanistas y ambientalistas en la planificación de obras de mitigación (como canales, diques o sistemas de drenaje) y en la evaluación de impacto ambiental.",
    "fuente": "gad",
    "geometria": "poligono",
    "punto": "",
    "poligono": "-2.109987 -79.411776 0 0;-2.110231 -79.411538 0 0;-2.110639 -79.411984 0 0;-2.110394 -79.412232 0 0;-2.109987 -79.411776 0 0",
    "archivo": "LA UNION INUNDACION-14_16_31.pdf",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/792563899/attachments/attF7erzEhSdnz6gqyVhVLMB/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_CZ5_SNGR_ZONAL_SNGR_CZ5_2026-PRELIM-F03-55ea2024-486d-43f6-b180-a6680a612b87-1",
    "parentIndex": 56,
    "provincia": "",
    "canton": "",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_CZ5_SNGR_ZONAL_SNGR_CZ5_2026",
    "fechaRegistro": 46199,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "Bases Aéreas y Navales en Guayaquil",
    "descripcion": "Se detallan todas las bases aéreas y navales que existen en Guayaquil, las mismas que presentan una insfraestructura y alcantarillado en malas condiciones lo que puede ocasionar inundaciones y debilitamiento de la infrastructura.",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-2.150927 -79.880443 0 0",
    "poligono": "",
    "archivo": "Captura de Pantalla 2026-06-26 a la(s) 10.49.14-23_17_34.png",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/794554009/attachments/atteKGnBKbmMtD8eiTdjBDwc/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_GUAYAQUIL_GAD_2026-PRELIM-F03-1bba822e-0dc7-44f3-9c97-d86c11564788-1",
    "parentIndex": 57,
    "provincia": "GUAYAS",
    "canton": "GUAYAQUIL",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_GUAYAQUIL_GAD_2026",
    "fechaRegistro": 46199,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "BASES AÉREAS Y NAVALES DE GUAYAQUIL",
    "descripcion": "PERMITE LA IDENTIFICACIÓN Y UBICACIÓN DE LAS BASES AÉREAS Y NAVALES EN LA CIUDAD DE GUAYAQUIL",
    "fuente": "gad",
    "geometria": "punto",
    "punto": "-2.163792 -79.884952 0 0",
    "poligono": "",
    "archivo": "Captura de Pantalla 2026-06-26 a la(s) 10.49.14-10_21_35.png",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/795968864/attachments/attv4JuNDvJwHydzDqpAPQTU/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": ""
  },
  {
    "id": "ENOS_Z5_GAD_CANTONAL_GUAYAS_BALAO_GAD_2026-PRELIM-F03-ce6728c2-e492-4a85-aa51-a6ff6e16a57b-1",
    "parentIndex": 58,
    "provincia": "GUAYAS",
    "canton": "BALAO",
    "institucion": "",
    "codigoCaso": "ENOS_Z5_GAD_CANTONAL_GUAYAS_BALAO_GAD_2026",
    "fechaRegistro": 46203,
    "tipo": "pdf",
    "formato": "imagen",
    "nombre": "Punto de intervención para la construcción del muro de contención.",
    "descripcion": "La información cartográfica obtenida mediante inspección técnica en campo permite identificar con precisión el tramo de la ribera afectado por procesos de erosión y desbordamiento del río.",
    "fuente": "campo",
    "geometria": "punto",
    "punto": "-2.909546 -79.817412 5 0.76",
    "poligono": "",
    "archivo": "Captura de pantalla 2026-07-02 095934-10_0_23.png",
    "archivoUrl": "https://kf.kobotoolbox.org/api/v2/assets/a86WYnMJZA3XCNJ8tcjQb2/data/800193604/attachments/att973xmEfoUt9yWvwLUpJaz/",
    "mapaUrl": "",
    "calidad": "80",
    "estadoCalidad": "suficiente_observada",
    "estadoValidacion": "",
    "amenaza": "",
    "prioridad": "",
    "comunidadSector": "",
    "limitaciones": "La ubicación del proyecto fue identificada mediante inspección técnica en campo y georreferenciada en la ribera del río. El área corresponde a un sector susceptible a procesos de erosión e inundación, donde se proyecta la construcción de un muro de contención como medida de mitigación para reducir la vulnerabilidad de la zona."
  }
];