window.SmartRisk=window.SmartRisk||{};(function(){const SR=SmartRisk;let currentHtml="";
function store(k,f){return SR.Storage.get(k,f)||f}
function data(){return{territories:store("territories",SR.MockData.territories||[]),institutions:store("institutions",SR.MockData.institutions||[]),sites:store("sites",SR.MockData.sites||[]),actions:store("actions",SR.MockData.actions||[])}}
function esc(v){return SR.Utils.escapeHtml(String(v??""))}
function unique(arr){return [...new Set(arr.filter(Boolean))].sort()}
function now(){return new Date().toLocaleDateString("es-EC",{year:"numeric",month:"long",day:"numeric"})}
function options(values,empty){return `<option value="">${empty}</option>${values.map(v=>`<option>${esc(v)}</option>`).join("")}`}
function filtered(){const d=data(),province=document.getElementById("r-provincia")?.value||"",canton=document.getElementById("r-canton")?.value||"",institution=document.getElementById("r-institucion")?.value||"";
const match=x=>(!province||x.provincia===province)&&(!canton||x.canton===canton);
return{actions:d.actions.filter(x=>match(x)&&(!institution||x.institucion===institution)),sites:d.sites.filter(match),institutions:d.institutions.filter(x=>(!province||x.provincia===province)&&(!canton||x.canton===canton)&&(!institution||x.nombre===institution||x.institucion===institution)),territories:d.territories.filter(match),province,canton,institution}}
function metrics(f){const a=f.actions,s=f.sites,i=f.institutions;const avg=Math.round(a.reduce((s,x)=>s+Number(x.avance||0),0)/Math.max(a.length,1));const blocked=a.filter(x=>String(x.estado).toLowerCase()==="bloqueada").length;const complete=a.filter(x=>String(x.estado).toLowerCase()==="completada").length;const priority=s.filter(x=>["alto","muy alto","crítico","critico"].includes(String(x.nivelRiesgo||x.riesgo||"").toLowerCase())).length;return{avg,blocked,complete,priority,actions:a.length,sites:s.length,institutions:i.length}}
function actionTable(rows){return `<table class="report-table"><thead><tr><th>Acción</th><th>Línea</th><th>Responsable</th><th>Estado</th><th>Avance</th></tr></thead><tbody>${rows.slice(0,20).map(x=>`<tr><td>${esc(x.titulo)}</td><td>${esc(x.linea)}</td><td>${esc(x.responsable)}</td><td>${esc(x.estado)}</td><td>${Number(x.avance||0)}%</td></tr>`).join("")||'<tr><td colspan="5">Sin acciones para los filtros seleccionados.</td></tr>'}</tbody></table>`}
function siteTable(rows){return `<table class="report-table"><thead><tr><th>Sitio</th><th>Cantón</th><th>Amenaza</th><th>Riesgo</th></tr></thead><tbody>${rows.slice(0,15).map(x=>`<tr><td>${esc(x.nombre||x.sitio||"Sin nombre")}</td><td>${esc(x.canton)}</td><td>${esc(x.amenaza||x.evento||"")}</td><td>${esc(x.nivelRiesgo||x.riesgo||"")}</td></tr>`).join("")||'<tr><td colspan="4">Sin sitios para los filtros seleccionados.</td></tr>'}</tbody></table>`}
function recommendations(f,m){const out=[];if(m.blocked)out.push(`Gestionar ${m.blocked} acciones bloqueadas mediante coordinación con las instituciones responsables.`);if(m.avg<80)out.push(`Fortalecer el seguimiento operativo, debido a que el avance promedio es ${m.avg}%.`);if(m.priority)out.push(`Priorizar la validación y tratamiento de ${m.priority} sitios con riesgo alto o crítico.`);if(!f.actions.length)out.push("Actualizar el registro de acciones para disponer de información de seguimiento.");if(!out.length)out.push("Mantener el seguimiento periódico y la actualización de evidencias.");return `<ol>${out.map(x=>`<li>${esc(x)}</li>`).join("")}</ol>`}
function generate(){const f=filtered(),m=metrics(f),type=document.getElementById("r-tipo").value,period=document.getElementById("r-periodo").value||"Período no especificado",title=document.getElementById("r-titulo").value.trim()||type,author=document.getElementById("r-responsable").value.trim()||"Coordinación Zonal 5",scope=[f.province,f.canton,f.institution].filter(Boolean).join(" · ")||"Cobertura zonal";
currentHtml=`<article class="report-document"><header class="report-header"><div class="report-brand"><h1>${esc(title)}</h1><p>SmartRisk CZ5 · Secretaría Nacional de Gestión de Riesgos</p></div><div class="report-meta"><strong>${esc(type)}</strong><br>${esc(period)}<br>${esc(now())}</div></header><section class="report-section"><h2>1. Información general</h2><p><strong>Ámbito:</strong> ${esc(scope)}</p><p><strong>Responsable de elaboración:</strong> ${esc(author)}</p><div class="report-note">El presente documento consolida la información disponible en los módulos operativos de SmartRisk CZ5 al momento de su generación.</div></section><section class="report-section"><h2>2. Resumen ejecutivo</h2><div class="report-kpis"><div class="report-kpi"><span>Acciones</span><strong>${m.actions}</strong></div><div class="report-kpi"><span>Avance promedio</span><strong>${m.avg}%</strong></div><div class="report-kpi"><span>Sitios</span><strong>${m.sites}</strong></div><div class="report-kpi"><span>Instituciones</span><strong>${m.institutions}</strong></div></div><p>Se identifican ${m.complete} acciones completadas, ${m.blocked} acciones bloqueadas y ${m.priority} sitios con nivel de riesgo alto o crítico.</p></section><section class="report-section"><h2>3. Seguimiento de acciones</h2>${actionTable(f.actions)}</section><section class="report-section"><h2>4. Sitios y condiciones territoriales</h2>${siteTable(f.sites)}</section><section class="report-section"><h2>5. Recomendaciones</h2>${recommendations(f,m)}</section><footer class="report-footer">Documento generado desde SmartRisk CZ5. La información debe ser validada por las unidades técnicas responsables antes de su emisión oficial.</footer></article>`;
document.getElementById("report-preview-root").innerHTML=currentHtml;SR.Toast.show("Vista previa generada.","success")}
function downloadWord(){if(!currentHtml)generate();const html=`<!doctype html><html><head><meta charset="utf-8"><title>Reporte SmartRisk CZ5</title><style>body{font-family:Arial,sans-serif;color:#1d2530}h1,h2{color:#193c59}table{width:100%;border-collapse:collapse;font-size:11px}th,td{border:1px solid #bbb;padding:6px;text-align:left}.report-kpis{display:flex;gap:8px}.report-kpi{border:1px solid #ccc;padding:8px;min-width:120px}.report-note{border-left:4px solid #244f72;padding:10px;background:#f4f6f8}</style></head><body>${currentHtml}</body></html>`;const blob=new Blob(["\ufeff",html],{type:"application/msword"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="reporte-smartrisk.doc";a.click();URL.revokeObjectURL(a.href);SR.Toast.show("Documento Word generado.","success")}
function render(){const d=data(),provinces=unique([...(d.actions||[]).map(x=>x.provincia),...(d.sites||[]).map(x=>x.provincia)]),cantons=unique([...(d.actions||[]).map(x=>x.canton),...(d.sites||[]).map(x=>x.canton)]),institutions=unique((d.institutions||[]).map(x=>x.nombre||x.institucion).concat((d.actions||[]).map(x=>x.institucion)));return `<section class="page-header"><div><span class="kicker">Producción documental</span><h1 class="page-title">Reportes Institucionales</h1><p class="page-subtitle">Construye informes con la información consolidada de acciones, sitios, instituciones e indicadores.</p></div><div class="split-actions"><button id="report-word" class="btn btn-secondary">${SR.Icon.render("file-text",17)}Exportar Word</button><button id="report-pdf" class="btn">${SR.Icon.render("printer",17)}Imprimir / PDF</button></div></section><section class="report-builder"><article class="panel"><header class="panel-header"><h2 class="section-title">Configuración</h2></header><div class="panel-body"><div class="report-form"><label class="form-field"><span class="form-label">Tipo de reporte</span><select id="r-tipo" class="select-input"><option>Informe de seguimiento mensual</option><option>Ficha ejecutiva</option><option>Informe técnico territorial</option><option>Reporte institucional</option></select></label><label class="form-field"><span class="form-label">Título</span><input id="r-titulo" class="form-input" placeholder="Título del documento"></label><label class="form-field"><span class="form-label">Período</span><input id="r-periodo" class="form-input" placeholder="Ej. julio de 2026"></label><label class="form-field"><span class="form-label">Provincia</span><select id="r-provincia" class="select-input">${options(provinces,"Todas las provincias")}</select></label><label class="form-field"><span class="form-label">Cantón</span><select id="r-canton" class="select-input">${options(cantons,"Todos los cantones")}</select></label><label class="form-field"><span class="form-label">Institución</span><select id="r-institucion" class="select-input">${options(institutions,"Todas las instituciones")}</select></label><label class="form-field"><span class="form-label">Responsable de elaboración</span><input id="r-responsable" class="form-input" placeholder="Nombre o unidad responsable"></label><button id="generate-report" class="btn">${SR.Icon.render("play",17)}Generar vista previa</button></div></div></article><div id="report-preview-root" class="report-preview"><div class="report-empty"><strong>Configure y genere el reporte.</strong><p>La vista previa aparecerá en este espacio.</p></div></div></section>`}
function bind(){document.getElementById("generate-report").onclick=generate;document.getElementById("report-word").onclick=downloadWord;document.getElementById("report-pdf").onclick=()=>{if(!currentHtml)generate();setTimeout(()=>window.print(),100)}}
SR.ReportesModule={route:{path:"/reportes",title:"Reportes",render,bind}}})();