window.SmartRisk=window.SmartRisk||{};(function(){const SR=SmartRisk;
const esc=v=>SR.Utils.escapeHtml(v??"");
function source(){return SR.ENOSData||{meta:{},gads:[]}}
function stats(rows){const f07={"Atribuible":0,"Conciliar":0,"Referencia":0,"Sin registro":0,"Sin detalle":0};rows.forEach(x=>f07[x.f07]=(f07[x.f07]||0)+1);return{total:rows.length,critical:rows.filter(x=>x.brecha==="CRÍTICO").length,high:rows.filter(x=>x.brecha==="ALTO").length,withF07:rows.filter(x=>Number(x.f07Registros)>0).length,evidence:rows.reduce((s,x)=>s+Number(x.f07Evidencias||0),0),linked:rows.reduce((s,x)=>s+Number(x.f07Vinculados||0),0),f07}}
function byProvince(rows){const m={};rows.forEach(x=>{const p=x.provincia||"Sin provincia";m[p]??={name:p,total:0,critical:0,withF07:0,attributed:0};m[p].total++;if(x.brecha==="CRÍTICO")m[p].critical++;if(Number(x.f07Registros)>0)m[p].withF07++;if(x.f07==="Atribuible")m[p].attributed++});return Object.values(m).sort((a,b)=>b.total-a.total)}
function kpis(s){return `<section class="executive-grid"><article class="executive-kpi"><span>Entidades revisadas</span><strong>${s.total}</strong><small>Universo CZ5 consolidado</small></article><article class="executive-kpi"><span>Brecha crítica</span><strong>${s.critical}</strong><small>${s.high} con brecha alta</small></article><article class="executive-kpi"><span>F07 detectados</span><strong>${s.withF07}</strong><small>${s.f07.Atribuible||0} con clasificación atribuible</small></article><article class="executive-kpi"><span>Evidencias F07</span><strong>${s.evidence}</strong><small>${s.linked} seguimientos con vínculo registrado</small></article></section>`}
function provinceTable(items){return `<div style="overflow:auto"><table class="executive-table"><thead><tr><th>Provincia</th><th>Entidades</th><th>Críticas</th><th>Con F07</th><th>F07 atribuible</th></tr></thead><tbody>${items.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${x.total}</td><td>${x.critical}</td><td>${x.withF07}</td><td>${x.attributed}</td></tr>`).join("")}</tbody></table></div>`}
function f07Matrix(s){const keys=["Atribuible","Conciliar","Referencia","Sin registro","Sin detalle"];return `<div class="executive-semaphore">${keys.filter(k=>(s.f07[k]||0)>0).map(k=>`<article class="semaphore-card"><strong>${s.f07[k]||0}</strong><span>${esc(k)}</span></article>`).join("")}</div>`}
function priorities(rows){const score=x=>x.brecha==="CRÍTICO"?2:1;return [...rows].filter(x=>x.f07!=="Atribuible"||x.brecha==="CRÍTICO").sort((a,b)=>score(b)-score(a)||b.f07Registros-a.f07Registros).slice(0,8)}
function priorityRows(rows){return `<div class="executive-alerts">${rows.map(x=>`<article class="executive-alert"><span class="executive-alert-icon">${SR.Icon.render(x.f07==="Sin registro"?"alert-triangle":"clock",18)}</span><div><h4>${esc(x.gad)}</h4><p>${esc(x.hallazgo)}</p></div><strong>${esc(x.f07)}</strong></article>`).join("")}</div>`}
function render(){const d=source(),rows=d.gads||[],s=stats(rows),p=byProvince(rows),m=d.meta||{};if(!rows.length)return `<section class="page-header"><div><h1 class="page-title">Dashboard Ejecutivo ENOS</h1><p class="page-subtitle">No se cargó la fuente ENOS.</p></div></section>`;return `<section class="page-header"><div><span class="kicker">ENOS 2026–2027 · fuente oficial de trabajo</span><h1 class="page-title">Dashboard Ejecutivo</h1><p class="page-subtitle">Consolidado de 56 GAD y entidades territoriales. Los registros “Referencia” no se interpretan como avance homologado.</p></div><div class="split-actions"><a class="btn btn-secondary" href="#/territorios">${SR.Icon.render("map",17)}Ver 56 GAD</a><button id="export-enos" class="btn">${SR.Icon.render("download",17)}Exportar</button></div></section><div class="indicator-note"><strong>Actualización de plataforma:</strong> ${esc(m.matrixUpdatedAt||"—")} · <strong>Corte de información F07:</strong> ${esc(m.f07Cutoff||"—")} · <strong>Autoauditoría:</strong> ${esc(m.auditDate||"—")}</div>${kpis(s)}<section class="executive-layout"><div class="executive-stack">${SR.Card.panel({title:"Cobertura por provincia",body:provinceTable(p)})}${SR.Card.panel({title:"Clasificación F07",body:f07Matrix(s)})}</div><div class="executive-stack">${SR.Card.panel({title:"Prioridades de revisión",body:priorityRows(priorities(rows))})}${SR.Card.panel({title:"Criterio de lectura",body:`<div class="stack"><div class="indicator-note"><strong>Atribuible:</strong> registro identificable para el GAD y componente.</div><div class="indicator-note"><strong>Conciliar:</strong> requiere resolver versiones, códigos o vínculos.</div><div class="indicator-note"><strong>Referencia:</strong> existe información, pero no debe computarse como avance homologado.</div><div class="indicator-note"><strong>Sin registro:</strong> no se localizó respuesta atribuible en el corte revisado.</div></div>`})}</div></section>`}
function bind(){document.getElementById("export-enos")?.addEventListener("click",()=>{const d=source();SR.Utils.downloadCsv("smartrisk-enos-56-gad.csv",d.gads.map(x=>({N:x.id,Provincia:x.provincia,GAD:x.gad,Brecha:x.brecha,F01:x.f01,F02:x.f02,F03:x.f03,F04:x.f04,F05:x.f05,F06:x.f06,F07:x.f07,"Registros F07":x.f07Registros,"Periodo F07":x.f07Periodo,"Evidencias F07":x.f07Evidencias,"Vinculados F07":x.f07Vinculados,Hallazgo:x.hallazgo})));SR.Toast.show("Matriz ENOS exportada.","success")})}
SR.DashboardModule={route:{path:"/dashboard",title:"Dashboard Ejecutivo",render,bind}}})();