window.SmartRisk=window.SmartRisk||{};(function(){const SR=SmartRisk;
function store(key,fallback){return SR.Storage.get(key,fallback)||fallback}
function norm(v){return String(v||"").trim().toLowerCase()}
function getData(){return{territories:store("territories",SR.MockData.territories||[]),institutions:store("institutions",SR.MockData.institutions||[]),sites:store("sites",SR.MockData.sites||[]),actions:store("actions",SR.MockData.actions||[])}}
function pct(n,d){return Math.round((n/Math.max(d,1))*100)}
function classify(v){return v>=80?["Alto","indicator-good"]:v>=50?["Medio","indicator-medium"]:["Bajo","indicator-bad"]}
function compute(d){const a=d.actions||[],s=d.sites||[],i=d.institutions||[],t=d.territories||[];
const completed=a.filter(x=>norm(x.estado)==="completada").length;
const active=a.filter(x=>["en ejecución","pendiente"].includes(norm(x.estado))).length;
const blocked=a.filter(x=>norm(x.estado)==="bloqueada").length;
const withResponsible=a.filter(x=>x.responsable&&norm(x.responsable)!=="sin responsable").length;
const withEvidence=a.filter(x=>(x.evidencias||[]).length>0).length;
const onTime=a.filter(x=>!x.fechaFin||new Date(x.fechaFin)>=new Date()||norm(x.estado)==="completada").length;
const avg=Math.round(a.reduce((sum,x)=>sum+Number(x.avance||0),0)/Math.max(a.length,1));
const highSites=s.filter(x=>["alto","muy alto","crítico","critico"].includes(norm(x.nivelRiesgo||x.riesgo))).length;
const validatedSites=s.filter(x=>["validado","verificado","completo"].includes(norm(x.estado||x.validacion))).length;
const instWithContact=i.filter(x=>x.responsable||x.contacto||x.email).length;
const territorialCoverage=new Set(a.map(x=>x.canton).filter(Boolean)).size;
const overall=Math.round((avg+pct(withResponsible,a.length)+pct(withEvidence,a.length)+pct(onTime,a.length))/4);
return{totalActions:a.length,completed,active,blocked,withResponsible,withEvidence,onTime,avg,highSites,validatedSites,totalSites:s.length,totalInstitutions:i.length,instWithContact,totalTerritories:t.length,territorialCoverage,overall,
indicators:[
{name:"Avance promedio de acciones",value:avg,target:80,source:"Acciones",interpretation:"Promedio porcentual reportado"},
{name:"Acciones con responsable",value:pct(withResponsible,a.length),target:100,source:"Acciones",interpretation:"Responsabilidad asignada"},
{name:"Acciones con evidencias",value:pct(withEvidence,a.length),target:90,source:"Acciones",interpretation:"Disponibilidad de soportes"},
{name:"Cumplimiento de plazos",value:pct(onTime,a.length),target:85,source:"Acciones",interpretation:"Acciones dentro de plazo o completadas"},
{name:"Instituciones con contacto",value:pct(instWithContact,i.length),target:100,source:"Instituciones",interpretation:"Capacidad de coordinación"},
{name:"Sitios validados",value:pct(validatedSites,s.length),target:80,source:"Sitios",interpretation:"Registros con validación técnica"}
]}}
function byProvince(d){const map={};(d.actions||[]).forEach(x=>{const p=x.provincia||"Sin provincia";if(!map[p])map[p]={name:p,total:0,progress:0,completed:0,blocked:0};map[p].total++;map[p].progress+=Number(x.avance||0);if(norm(x.estado)==="completada")map[p].completed++;if(norm(x.estado)==="bloqueada")map[p].blocked++});return Object.values(map).map(x=>({...x,avg:Math.round(x.progress/Math.max(x.total,1)),compliance:pct(x.completed,x.total)})).sort((a,b)=>b.avg-a.avg)}
function cards(m){return `<section class="indicator-grid"><article class="indicator-card"><span>Índice global</span><strong>${m.overall}%</strong><small>Resultado consolidado</small></article><article class="indicator-card"><span>Avance promedio</span><strong>${m.avg}%</strong><small>${m.totalActions} acciones registradas</small></article><article class="indicator-card"><span>Cobertura cantonal</span><strong>${m.territorialCoverage}</strong><small>Cantones con acciones</small></article><article class="indicator-card"><span>Sitios prioritarios</span><strong>${m.highSites}</strong><small>Riesgo alto o crítico</small></article></section>`}
function indicatorRows(items){return items.map(x=>{const [label,cls]=classify(x.value);return `<div class="indicator-row"><div><strong>${x.name}</strong><small class="muted" style="display:block;margin-top:3px">${x.interpretation}</small></div><div class="indicator-progress"><span style="width:${Math.min(100,x.value)}%"></span></div><strong>${x.value}%</strong><span class="indicator-badge ${cls}">${label}</span></div>`}).join("")}
function matrix(rows){return `<div style="overflow:auto"><table class="indicator-matrix"><thead><tr><th>Provincia</th><th>Acciones</th><th>Avance</th><th>Completadas</th><th>Bloqueadas</th><th>Cumplimiento</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.total}</td><td>${x.avg}%</td><td>${x.completed}</td><td>${x.blocked}</td><td>${x.compliance}%</td></tr>`).join("")||'<tr><td colspan="6">Sin datos.</td></tr>'}</tbody></table></div>`}
function recommendations(m){const notes=[];if(m.avg<80)notes.push("El avance promedio está por debajo de la meta operativa del 80%.");if(m.withEvidence<m.totalActions)notes.push(`${m.totalActions-m.withEvidence} acciones no tienen evidencias registradas.`);if(m.blocked>0)notes.push(`${m.blocked} acciones están bloqueadas y requieren gestión institucional.`);if(m.instWithContact<m.totalInstitutions)notes.push(`${m.totalInstitutions-m.instWithContact} instituciones no cuentan con contacto o responsable completo.`);if(m.highSites>0)notes.push(`${m.highSites} sitios presentan nivel de riesgo alto o crítico.`);if(!notes.length)notes.push("Los indicadores principales se encuentran dentro de los rangos esperados.");return notes.map(x=>`<div class="indicator-note">${x}</div>`).join("")}
function render(){const d=getData(),m=compute(d),p=byProvince(d);return `<section class="page-header"><div><span class="kicker">Cálculo y seguimiento</span><h1 class="page-title">Motor de Indicadores</h1><p class="page-subtitle">Calcula automáticamente indicadores de cumplimiento, calidad de datos y avance territorial con la información registrada.</p></div><div class="split-actions"><button id="recalc-indicators" class="btn btn-secondary">${SR.Icon.render("refresh-cw",17)}Recalcular</button><button id="export-indicators" class="btn">${SR.Icon.render("download",17)}Exportar matriz</button></div></section>${cards(m)}<section class="indicator-layout"><div class="indicator-stack">${SR.Card.panel({title:"Indicadores principales",body:indicatorRows(m.indicators)})}${SR.Card.panel({title:"Consolidado provincial",body:matrix(p)})}</div><div class="indicator-stack">${SR.Card.panel({title:"Lectura ejecutiva",body:recommendations(m)})}${SR.Card.panel({title:"Metodología aplicada",body:`<div class="stack"><p class="muted">Los indicadores se calculan con los datos locales disponibles en los módulos Acciones, Instituciones y Sitios.</p><div class="indicator-note"><strong>Escala:</strong> Alto ≥ 80%; Medio entre 50% y 79%; Bajo &lt; 50%.</div><div class="indicator-note"><strong>Índice global:</strong> promedio de avance, asignación de responsables, evidencias y cumplimiento de plazos.</div><div class="indicator-note"><strong>Actualización:</strong> los valores cambian cuando se modifican los registros operativos.</div></div>`})}</div></section>`}
function bind(){document.getElementById("recalc-indicators")?.addEventListener("click",()=>{SR.Toast.show("Indicadores recalculados.","success");location.reload()});document.getElementById("export-indicators")?.addEventListener("click",()=>{const d=getData(),m=compute(d),p=byProvince(d);const rows=[...m.indicators.map(x=>({Tipo:"Indicador",Nombre:x.name,Valor:x.value+"%",Meta:x.target+"%",Fuente:x.source})),...p.map(x=>({Tipo:"Provincia",Nombre:x.name,Valor:x.avg+"%",Meta:"80%",Fuente:"Acciones"}))];SR.Utils.downloadCsv("indicadores-smartrisk.csv",rows);SR.Toast.show("Matriz de indicadores exportada.","success")})}
SR.IndicadoresModule={route:{path:"/indicadores",title:"Indicadores",render,bind}}})();