(() => {
 const DATA=window.SR_CONSULTORIA_DATA, OPS=window.SR_OPERATIONS; const state={selected:'milagro',tab:'boreholes',data:null};
 const $=id=>document.getElementById(id); const project=()=>DATA.projects.find(p=>p.id===state.selected)||DATA.projects[0];
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function statusClass(s){return /no conforme|abierta|repetir/i.test(s||'')?'bad':/pendiente|proceso|envío/i.test(s||'')?'warn':'';}
 async function load(){state.data=await OPS.load(project().id);renderAll();}
 function renderProjects(){ $('opsProjectList').innerHTML=DATA.projects.map(p=>`<button class="ops-project ${p.id===state.selected?'active':''}" data-p="${p.id}"><strong>${esc(p.canton)}</strong><small style="display:block;color:var(--muted);margin-top:3px">${esc(p.code)} · ${esc(p.stage)}</small></button>`).join(''); $('opsProjectList').querySelectorAll('[data-p]').forEach(b=>b.addEventListener('click',async()=>{state.selected=b.dataset.p;await load();})); }
 function renderKpis(){const s=OPS.summarize(state.data);$('opsKpis').innerHTML=[['Perforación',`${s.drillingProgress}%`,`${s.executed}/${s.planned} m`],['Muestras pendientes',s.pendingSamples,'cadena/laboratorio'],['Geofísica',`${s.geoDone}/${s.geoTotal}`,'procesadas/completadas'],['No conformidades',s.nonConformities,'QA/QC abiertas'],['Gate proyecto',project().gate,project().stage]].map(([l,v,x])=>`<article class="kpi card"><span>${l}</span><strong>${v}</strong><small>${x}</small></article>`).join('');}
 function header(title,sub,button=''){return `<div class="panel-header"><div><div class="panel-title">${title}</div><div class="panel-subtitle">${sub}</div></div>${button}</div>`;}
 function boreholes(){const rows=state.data.boreholes.map(x=>`<tr><td><strong>${esc(x.id)}</strong><br><small>${esc(x.site)}</small></td><td>${x.planned} m</td><td>${x.executed} m</td><td>${x.spt}</td><td>${x.samples}</td><td>${x.rock} m</td><td><span class="status-pill ${statusClass(x.status)}">${esc(x.status)}</span></td></tr>`).join('');return `${header('Perforaciones y SPT',project().code,'<button class="btn primary" data-add-borehole>＋ Registro</button>')}<div class="table-wrap"><table class="ops-table"><thead><tr><th>Punto</th><th>Plan</th><th>Ejecutado</th><th>SPT</th><th>Muestras</th><th>Roca</th><th>Estado</th></tr></thead><tbody>${rows||'<tr><td colspan="7">Sin registros.</td></tr>'}</tbody></table></div><div id="opsForm"></div>`;}
 function samples(){const rows=state.data.samples.map(x=>`<tr><td><strong>${esc(x.id)}</strong></td><td>${esc(x.borehole)}</td><td>${esc(x.depth)}</td><td>${esc(x.custody)}</td><td>${esc((x.tests||[]).join(', '))}</td><td><span class="status-pill ${statusClass(x.status)}">${esc(x.status)}</span></td></tr>`).join('');return `${header('Muestras y laboratorio','Cadena de custodia → ensayo → resultado','<button class="btn primary" data-add-sample>＋ Muestra</button>')}<div class="table-wrap"><table class="ops-table"><thead><tr><th>Muestra</th><th>Perforación</th><th>Profundidad</th><th>Custodia</th><th>Ensayos</th><th>Estado</th></tr></thead><tbody>${rows||'<tr><td colspan="6">Sin muestras registradas.</td></tr>'}</tbody></table></div><div id="opsForm"></div>`;}
 function geophysics(){const rows=state.data.geophysics.map(x=>`<tr><td><strong>${esc(x.id)}</strong></td><td>${esc(x.type)}</td><td>${esc(x.site)}</td><td>${esc(x.value)}</td><td><span class="status-pill ${statusClass(x.status)}">${esc(x.status)}</span></td><td><span class="status-pill ${statusClass(x.qa)}">${esc(x.qa)}</span></td></tr>`).join('');return `${header('Geofísica','Vs30/Vs40 · HVSR/Nakamura · control instrumental','<button class="btn primary" data-add-geophysics>＋ Punto</button>')}<div class="table-wrap"><table class="ops-table"><thead><tr><th>ID</th><th>Método</th><th>Sitio</th><th>Resultado</th><th>Estado</th><th>QA</th></tr></thead><tbody>${rows||'<tr><td colspan="6">Sin registros geofísicos.</td></tr>'}</tbody></table></div><div id="opsForm"></div>`;}
 function sig(){const rows=state.data.sig.map(x=>`<tr><td><strong>${esc(x.id)}</strong></td><td>${esc(x.product)}</td><td>${esc(x.version)}</td><td><span class="status-pill ${statusClass(x.status)}">${esc(x.status)}</span></td><td><span class="status-pill ${statusClass(x.qa)}">${esc(x.qa)}</span></td></tr>`).join('');return `${header('SIG y modelación','Integración geoespacial, superficies, microzonas y modelos')}<div class="table-wrap"><table class="ops-table"><thead><tr><th>ID</th><th>Producto</th><th>Versión</th><th>Estado</th><th>QA</th></tr></thead><tbody>${rows||'<tr><td colspan="5">Sin productos SIG registrados.</td></tr>'}</tbody></table></div>`;}
 function qaqc(){const rows=state.data.qaqc.map(x=>`<tr><td><strong>${esc(x.id)}</strong></td><td>${esc(x.area)}</td><td>${esc(x.finding)}</td><td>${esc(x.severity)}</td><td>${esc(x.owner)}</td><td><span class="status-pill ${statusClass(x.status)}">${esc(x.status)}</span></td></tr>`).join('');return `${header('QA/QC técnico','No conformidades, observaciones y cierre independiente','<button class="btn primary" data-add-qaqc>＋ Hallazgo</button>')}<div class="table-wrap"><table class="ops-table"><thead><tr><th>ID</th><th>Área</th><th>Hallazgo</th><th>Severidad</th><th>Responsable</th><th>Estado</th></tr></thead><tbody>${rows||'<tr><td colspan="6">Sin hallazgos QA/QC.</td></tr>'}</tbody></table></div><div id="opsForm"></div>`;}
 function renderPanel(){const map={boreholes,samples,geophysics,sig,qaqc};$('opsPanel').innerHTML=(map[state.tab]||boreholes)();bindForms();}
 function bindForms(){
  $('opsPanel').querySelector('[data-add-borehole]')?.addEventListener('click',()=>showForm('boreholes'));
  $('opsPanel').querySelector('[data-add-sample]')?.addEventListener('click',()=>showForm('samples'));
  $('opsPanel').querySelector('[data-add-geophysics]')?.addEventListener('click',()=>showForm('geophysics'));
  $('opsPanel').querySelector('[data-add-qaqc]')?.addEventListener('click',()=>showForm('qaqc'));
 }
 function showForm(type){const f=$('opsForm'); if(!f)return; const templates={
  boreholes:`<div class="section-box"><div class="ops-form"><label class="field"><span>ID</span><input id="f1" placeholder="P-05"></label><label class="field"><span>Sitio</span><input id="f2"></label><label class="field"><span>Profundidad planificada</span><input id="f3" type="number" value="25"></label></div><button class="btn primary" id="saveOp">Guardar</button></div>`,
  samples:`<div class="section-box"><div class="ops-form"><label class="field"><span>ID muestra</span><input id="f1"></label><label class="field"><span>Perforación</span><input id="f2"></label><label class="field"><span>Profundidad</span><input id="f3"></label></div><button class="btn primary" id="saveOp">Guardar</button></div>`,
  geophysics:`<div class="section-box"><div class="ops-form"><label class="field"><span>ID</span><input id="f1"></label><label class="field"><span>Método</span><select id="f2"><option>Vs30/Vs40</option><option>HVSR</option></select></label><label class="field"><span>Sitio</span><input id="f3"></label></div><button class="btn primary" id="saveOp">Guardar</button></div>`,
  qaqc:`<div class="section-box"><div class="ops-form"><label class="field"><span>ID hallazgo</span><input id="f1"></label><label class="field"><span>Área</span><input id="f2"></label><label class="field"><span>Hallazgo</span><input id="f3"></label></div><button class="btn primary" id="saveOp">Guardar</button></div>`}; f.innerHTML=templates[type]; $('saveOp').addEventListener('click',async()=>{let r;if(type==='boreholes')r={id:$('f1').value,site:$('f2').value,planned:Number($('f3').value),executed:0,status:'Pendiente',spt:0,samples:0,rock:0};if(type==='samples')r={id:$('f1').value,borehole:$('f2').value,depth:$('f3').value,custody:'Campo',tests:[],status:'Pendiente envío'};if(type==='geophysics')r={id:$('f1').value,type:$('f2').value,site:$('f3').value,status:'Planificado',value:'Pendiente',qa:'Pendiente'};if(type==='qaqc')r={id:$('f1').value,area:$('f2').value,finding:$('f3').value,severity:'Media',owner:'tecnico',status:'Abierta'};await OPS.save(project().id,type,r);await load();}); }
 function renderAll(){renderProjects();renderKpis();renderPanel();}
 document.querySelectorAll('[data-ops-tab]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-ops-tab]').forEach(x=>x.classList.toggle('active',x===b));state.tab=b.dataset.opsTab;renderPanel();}));
 load();
})();