window.SmartRisk=window.SmartRisk||{};(function(){const SR=SmartRisk;
function safeStore(key,fallback){return SR.Storage.get(key,fallback)||fallback}
function normalizeState(v){return String(v||"").toLowerCase()}
function data(){return{territories:safeStore("territories",SR.MockData.territories||[]),institutions:safeStore("institutions",SR.MockData.institutions||[]),sites:safeStore("sites",SR.MockData.sites||[]),actions:safeStore("actions",SR.MockData.actions||[])}}
function metrics(d){const actions=d.actions||[],sites=d.sites||[],institutions=d.institutions||[],territories=d.territories||[];const avg=Math.round(actions.reduce((s,x)=>s+Number(x.avance||0),0)/Math.max(actions.length,1));const critical=sites.filter(x=>["alto","muy alto","crítico","critico"].includes(normalizeState(x.nivelRiesgo||x.riesgo))).length;const overdue=actions.filter(x=>x.fechaFin&&new Date(x.fechaFin)<new Date()&&!["completada"].includes(normalizeState(x.estado))).length;return{territories:territories.length,institutions:institutions.length,sites:sites.length,actions:actions.length,avg,critical,overdue,blocked:actions.filter(x=>normalizeState(x.estado)==="bloqueada").length}}
function provinceStats(d){const map={};(d.actions||[]).forEach(x=>{const p=x.provincia||"Sin provincia";if(!map[p])map[p]={name:p,actions:0,total:0,blocked:0};map[p].actions++;map[p].total+=Number(x.avance||0);if(normalizeState(x.estado)==="bloqueada")map[p].blocked++});return Object.values(map).map(x=>({...x,avg:Math.round(x.total/Math.max(x.actions,1))})).sort((a,b)=>b.avg-a.avg)}
function cantonStats(d){const map={};(d.actions||[]).forEach(x=>{const c=x.canton||"Sin cantón";if(!map[c])map[c]={name:c,actions:0,total:0,high:0};map[c].actions++;map[c].total+=Number(x.avance||0);if(x.prioridad==="Alta")map[c].high++});return Object.values(map).map(x=>({...x,avg:Math.round(x.total/Math.max(x.actions,1))})).sort((a,b)=>a.avg-b.avg).slice(0,8)}
function actionStates(d){const states={"Pendiente":0,"En ejecución":0,"Completada":0,"Bloqueada":0};(d.actions||[]).forEach(x=>states[x.estado]=(states[x.estado]||0)+1);return states}
function alerts(d,m){const a=[];(d.actions||[]).filter(x=>normalizeState(x.estado)==="bloqueada").slice(0,3).forEach(x=>a.push({icon:"alert-triangle",title:"Acción bloqueada",text:`${x.titulo} · ${x.canton}`,value:`${x.avance}%`}));(d.actions||[]).filter(x=>x.fechaFin&&new Date(x.fechaFin)<new Date()&&normalizeState(x.estado)!=="completada").slice(0,3).forEach(x=>a.push({icon:"clock",title:"Plazo vencido",text:`${x.titulo} · ${x.responsable}`,value:x.fechaFin}));(d.sites||[]).filter(x=>["alto","muy alto","crítico","critico"].includes(normalizeState(x.nivelRiesgo||x.riesgo))).slice(0,2).forEach(x=>a.push({icon:"map-pin",title:"Sitio prioritario",text:`${x.nombre||x.sitio||"Sitio"} · ${x.canton||""}`,value:x.nivelRiesgo||x.riesgo||"Alto"}));if(!a.length)a.push({icon:"check-circle",title:"Sin alertas críticas",text:"No se detectan bloqueos ni vencimientos con los datos actuales.",value:"OK"});return a.slice(0,6)}
function kpis(m){return `<section class="executive-grid"><article class="executive-kpi"><span>Avance operativo</span><strong>${m.avg}%</strong><small>Promedio de acciones</small></article><article class="executive-kpi"><span>Sitios registrados</span><strong>${m.sites}</strong><small>${m.critical} de atención prioritaria</small></article><article class="executive-kpi"><span>Instituciones</span><strong>${m.institutions}</strong><small>Actores en la plataforma</small></article><article class="executive-kpi"><span>Alertas operativas</span><strong>${m.blocked+m.overdue}</strong><small>${m.blocked} bloqueadas · ${m.overdue} vencidas</small></article></section>`}
function bars(items){const max=Math.max(...items.map(x=>x.avg),100);return `<div class="executive-chart">${items.map(x=>`<div class="executive-bar-row"><span class="executive-bar-label" title="${x.name}">${x.name}</span><div class="executive-bar-track"><div class="executive-bar-value" style="width:${Math.max(2,x.avg)}%"></div></div><strong>${x.avg}%</strong></div>`).join("")||'<p class="muted">Sin datos disponibles.</p>'}</div>`}
function ranking(items){return `<div style="overflow:auto"><table class="executive-table"><thead><tr><th>Cantón</th><th>Acciones</th><th>Prioridad alta</th><th>Avance</th></tr></thead><tbody>${items.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${x.actions}</td><td>${x.high}</td><td><div class="executive-progress"><div class="executive-progress-track"><div class="executive-progress-value" style="width:${x.avg}%"></div></div><strong>${x.avg}%</strong></div></td></tr>`).join("")||'<tr><td colspan="4">Sin datos.</td></tr>'}</tbody></table></div>`}
function alertList(items){return `<div class="executive-alerts">${items.map(x=>`<article class="executive-alert"><span class="executive-alert-icon">${SR.Icon.render(x.icon,18)}</span><div><h4>${x.title}</h4><p>${x.text}</p></div><strong>${x.value}</strong></article>`).join("")}</div>`}
function activity(d){const rows=[...(d.actions||[]).slice(-4).map(x=>({t:`Acción: ${x.titulo}`,s:`${x.canton} · ${x.estado}`})),...(d.sites||[]).slice(-2).map(x=>({t:`Sitio: ${x.nombre||x.sitio||"Registro territorial"}`,s:`${x.canton||""} · ${x.nivelRiesgo||x.riesgo||""}`}))].slice(0,6);return `<div class="executive-activity">${rows.map(x=>`<div class="executive-activity-item"><span class="executive-activity-dot"></span><div><p><strong>${x.t}</strong></p><small>${x.s}</small></div></div>`).join("")||'<p class="muted">Sin actividad disponible.</p>'}</div>`}
function render(){const d=data(),m=metrics(d),provinces=provinceStats(d),cantons=cantonStats(d),states=actionStates(d),a=alerts(d,m);return `<section class="page-header"><div><span class="kicker">Centro de monitoreo zonal</span><h1 class="page-title">Dashboard Ejecutivo</h1><p class="page-subtitle">Lectura consolidada de territorios, instituciones, sitios y acciones para apoyar la priorización y el seguimiento.</p></div><div class="split-actions"><button id="refresh-dashboard" class="btn btn-secondary">${SR.Icon.render("refresh-cw",17)}Actualizar</button><button id="export-dashboard" class="btn">${SR.Icon.render("download",17)}Exportar resumen</button></div></section>${kpis(m)}<section class="executive-layout"><div class="executive-stack">${SR.Card.panel({title:"Avance por provincia",body:bars(provinces)})}${SR.Card.panel({title:"Cantones que requieren mayor seguimiento",body:ranking(cantons)})}${SR.Card.panel({title:"Distribución operativa",body:`<div class="executive-semaphore"><article class="semaphore-card semaphore-low"><strong>${states["Completada"]||0}</strong><span>Completadas</span></article><article class="semaphore-card semaphore-medium"><strong>${(states["Pendiente"]||0)+(states["En ejecución"]||0)}</strong><span>En gestión</span></article><article class="semaphore-card semaphore-high"><strong>${states["Bloqueada"]||0}</strong><span>Bloqueadas</span></article></div>`})}</div><div class="executive-stack">${SR.Card.panel({title:"Alertas ejecutivas",body:alertList(a)})}${SR.Card.panel({title:"Actividad reciente",body:activity(d)})}${SR.Card.panel({title:"Accesos rápidos",body:`<div class="stack"><a class="btn btn-secondary" href="#/acciones">${SR.Icon.render("check-square",17)}Seguimiento de acciones</a><a class="btn btn-secondary" href="#/sitios">${SR.Icon.render("map-pin",17)}Revisar sitios</a><a class="btn btn-secondary" href="#/instituciones">${SR.Icon.render("building",17)}Revisar instituciones</a><a class="btn btn-secondary" href="#/territorios">${SR.Icon.render("map",17)}Revisar territorios</a></div>`})}</div></section>`}
function bind(){document.getElementById("refresh-dashboard")?.addEventListener("click",()=>{SR.Toast.show("Dashboard actualizado con los datos locales.","success");location.reload()});document.getElementById("export-dashboard")?.addEventListener("click",()=>{const d=data(),m=metrics(d);SR.Utils.downloadCsv("resumen-ejecutivo-smartrisk.csv",[{"Indicador":"Territorios","Valor":m.territories},{"Indicador":"Instituciones","Valor":m.institutions},{"Indicador":"Sitios","Valor":m.sites},{"Indicador":"Acciones","Valor":m.actions},{"Indicador":"Avance promedio","Valor":m.avg+"%"},{"Indicador":"Sitios prioritarios","Valor":m.critical},{"Indicador":"Acciones bloqueadas","Valor":m.blocked},{"Indicador":"Acciones vencidas","Valor":m.overdue}]);SR.Toast.show("Resumen ejecutivo exportado.","success")})}
SR.DashboardModule={route:{path:"/",title:"Dashboard Ejecutivo",render,bind}}})();